### ISSUE TITLE
[Feature]: Lsp provider should be a table or a string

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#1107]
### Feature motivation

some langs need multiple lang servers

### Describe the expected solution

so we will loop through the table and set them or if it's just a string set the one

### Describe the alternatives you've considered

none

**Comment by dklymenk** [comment]
Hello, I have actually added some code to `lua/lsp/init.lua` that solved this issue for me locally:

```diff
diff --git a/lua/lsp/init.lua b/lua/lsp/init.lua
index 827753c..5ec2e02 100644
--- a/lua/lsp/init.lua
+++ b/lua/lsp/init.lua
@@ -337,7 +337,19 @@ function lsp_config.setup(lang)
     end
   end

-  require("lspconfig")[provider].setup(lang_server.setup)
+  -- If provider is nil assume that an array of lang servers is supplied
+  if provider == nil then
+    for _, single_lang_server in pairs(lang_server) do
+      if not require("lv-utils").check_lsp_client_active(provider) then
+          require("lspconfig")[single_lang_server.provider].setup(single_lang_server.setup)
+      end
+    end
+  else
+    if require("lv-utils").check_lsp_client_active(provider) then
+      return
+    end
+    require("lspconfig")[provider].setup(lang_server.setup)
+  end
 end

 return lsp_config
 ```
 
 What this allowed me to do is to set 2 lang servers for php without overwriting default config for the rest of the languages in my `lv-config.lua` like this:
 ```lua
 lvim.lang.php.lsp = {
  intelephense = {
    provider = "intelephense",
    setup = {
      cmd = {
        DATA_PATH .. "/lspinstall/php/node_modules/.bin/intelephense",
        "--stdio",
      },
      filetypes = { "php", "phtml" },
      settings = {
        intelephense = {
          environment = {
            phpVersion = "7.4",
          },
        },
      },
    },
  },
  phpactor = {
    provider = "phpactor",
    setup = {
      handlers = {
        -- rely on intelephense for hover
        ["textDocument/hover"] = function() end,
      },
    },
  },
}
```

This not ideal and IMO we don't need a `provider` key in each lang server table. Instead we can use a structure like the one I have above for every single language and then have a simple loop like this running and iterating over all the lang servers for a particular language:

```lua
local lang_servers = lvim.lang[lang].lsp

for provider, lang_server in pairs(lang_servers) do
  if not require("lv-utils").check_lsp_client_active(provider) then
      require("lspconfig")[provider].setup(single_lang_server.setup)
  end
end
```

Notice how we use lang server key instead of provider key inside the lang server table.

I can work on PR for this if that would be ok.

> so we will loop through the table and set them or if it's just a string set the one

One reason I don't like this approach is that for each provider you might want to have different `setup` table and I assume that this is most likely the case for every other language where one would want to have his own handlers or cmd.

**Comment by dklymenk** [comment]
Hello @ChristianChiarulli , my previous proposal is no longer relevant because of how fast the codebase changes, so here is my latest take on the issue.

I still believe it's a good idea to have your multiple lsp configs stored like this (a php example I tested with):
```lua
lvim.lang.php.lsp = {
  intelephense = {
    provider = "intelephense", -- we shouldn't need this line anymore because we can use the key above for provider name
    setup = {
      cmd = {
        DATA_PATH .. "/lspinstall/php/node_modules/.bin/intelephense",
        "--stdio",
      },
      filetypes = { "php", "phtml" },
      settings = {
        intelephense = {
          environment = {
            phpVersion = "7.4",
          },
        },
      },
    },
  },
  phpactor = {
    provider = "phpactor",  -- we shouldn't need this line anymore because we can use the key above for provider name
    setup = {
      handlers = {
        -- rely on intelephense for hover
        ["textDocument/hover"] = function() end,
      },
    },
  },
}
```

However to make it so none of the old single provider configurations break we need some code to normalize them into tables of providers. Here is my latest code for `M.setup` in `lua/lsp/init.lua`:
```lua
function M.setup(lang)
  local lsp = lvim.lang[lang].lsp

  -- normalize the lsp config to be a table of providers
  if lsp['provider'] ~= nil then
    lsp = {[lsp.provider] = lsp}
  end

  -- initialize language server for each provider
  for provider, single_lang_server in pairs(lsp) do
    if not require("utils").check_lsp_client_active(provider) then
        require("lspconfig")[provider].setup(single_lang_server.setup)
    end
  end
end
```

Looks nice and clean. I hope you get to take a look at this before it becomes irrelevant.

**Comment by dklymenk** [comment]
Hello, I have submitted a PR #1204 for this.

**Comment by abzcoding** [comment]
you can achieve this in your own config, we might not need it in core
reference : https://github.com/LunarVim/LunarVim/pull/1204#issuecomment-902126277
