### ISSUE TITLE
[Feature]: Ability to open file from within lazygit, without nesting lunarvim instances

### ISSUE THREAD

**Issue by marcusbuffett** [LunarVim/LunarVim#1346]
Often when reviewing the pending changes in lazygit, I'll want to edit the file, and that ends up opening a new popup with a new instance of lunarvim. I'd like it if it just used the existing instance. This may require some sort of integration w/ lazygit.

**Comment by vlcinsky** [comment]
It would be great start.

As off-topic idea: Fugitive from tpope allows to open many git objects and views which lazygit deals with (current/historical commits, diffs etc). It would be great to let lazygit within neovim to allow opening these things within neovim. (someone shall open relevant issue if we shall discuss it, I feel it is a bit too early now).

Back to the topic: lazygit customization can be done via config file and I personally keep separate lazygit config for console usage and another for lunervim, mainy because some nice pagers (such as delta) do not work well when used within neovim.

**Comment by NikoKS** [comment]
As a temporary solution, I'm using [neovim-remote](https://github.com/mhinz/neovim-remote) as the editor for lazygit. Specifically the command `nvr --nostart --servername $NVIM_LISTEN_ADDRESS --remote-silent -l`. This would send the file to the existing neovim instance.

@vlcinsky How do you use different lazygit config for console and lunarvim?

**Comment by kylo252** [comment]
> How do you use different lazygit config for console and lunarvim?

You can pass an argument `--use-config-dir`.

**Comment by vlcinsky** [comment]
@NikoKS I am using following alias:
```bash
alias lg='lazygit -ucd /home/javl/.config/lazygit-lg'
```
This allows me to call lazygit as `lg`

**Comment by Nivethan-Ar** [comment]
for me lazygit opens my neovim instead of lunarvim! any solution for this?

**Comment by shelper** [comment]
@Nivethan-Ar i think you can change that in the config of lazygit https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#configuring-file-editing
