### ISSUE TITLE
[Bug]: Spacing does not respect formatter settings

### ISSUE THREAD

**Issue by gikari** [LunarVim/LunarVim#1364]
### Problem description

I use C++, so the steps are for that language:

1. Open CPP file with Clangd LSP or clang_format formatter turned on. The setting in `.clang-format` specify 4 spaces.
    ![Screenshot_20210820_160051](https://user-images.githubusercontent.com/14205339/130237037-450d5883-5102-49d4-8b8a-59a0fe5549fd.png)
2. LunarVim setting is set to 2 spaces.
    ![Screenshot_20210820_160123](https://user-images.githubusercontent.com/14205339/130237108-b238972a-13fe-4561-b9c7-80ac0e0fe108.png)

The spacing setting in LunarVim should match the formatter spacing setting.

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
This is not trivial to achieve, since you need to be able to parse that `.clang-format` file in the first place. You can always set these settings globally using `ftplugin` or maybe using `on_attach` for the language-server per project.

Related plugins to consider: 
- "Dumb automatic fast indentation detection for Neovim written in Lua":  https://github.com/Darazaki/indent-o-matic
- "EditorConfig plugin for Neovim": https://github.com/gpanders/editorconfig.nvim

**Comment by marcos-venicius** [comment]
this works to my case

```lua
vim.api.nvim_create_autocmd("BufEnter", {
  pattern = { "*.cs" },
  command = "setlocal tabstop=4 shiftwidth=4"
})
```
