### ISSUE TITLE
[Feature]: Improve startup time

### ISSUE THREAD

**Issue by ashincoder** [LunarVim/LunarVim#1418]
### Feature motivation

TO increase startup time. and make LV feel snappier

### Describe the expected solution

1. Improve startup time by disabling shada and lazy loading plugins 10 or 15 ms after startup load
2. cache modules using `impatient.nvim`

### Describe the alternatives you've considered

https://github.com/lewis6991/impatient.nvim
https://github.com/tjdevries/lazy.nvim

These plugins may be WIP. But bringing it to the community's attention might be able to make these as good as possible. 

### Additional context

Love ur project have a nice day. :+1: :smile:  (thank you sir)

**Comment by abzcoding** [comment]
thank you for mentioning this, i've changed it a bit if you don't mind

**Comment by abzcoding** [comment]
we can use sth like this in our `init.lua`
```lua
vim.cmd [[
  syntax off
  filetype off
  filetype plugin indent off
]]

vim.opt.shadafile = "NONE"
vim.g.loaded_gzip = false
vim.g.loaded_netrwPlugin = false
-- you get the point

require "core"
-- require things except plugins

vim.defer_fn(function()
  require "plugins"
  vim.opt.shadafile = ""
  vim.cmd [[
    rshada!
    doautocmd BufRead
    syntax on
    filetype on
    filetype plugin indent on
    PackerLoad nvim-treesitter
  ]]
  vim.defer_fn(function()
    vim.cmd [[
      PackerLoad plenary.nvim
      PackerLoad popup.nvim
      PackerLoad which-key.nvim
      PackerLoad nvim-lspconfig
      PackerLoad vim-matchup
      -- PackerLoad other stuff
      silent! bufdo e
    ]]
  end, 15)
end, 0)
```

**Comment by ashincoder** [comment]
yeah and also this one.
```lua
function M.lazy_load(plugin, timer)
   if plugin then
      timer = timer or 0
      vim.defer_fn(function()
         require("packer").loader(plugin)
      end, timer)
   end
end
```

**Comment by abzcoding** [comment]
yeah i keep this pinned, but we might need a bit of time before implementing it
first we need a solid stable 1.0 release 😅

**Comment by rafamadriz** [comment]
> we can use sth like this in our `init.lua`
> 
> ```lua
> vim.cmd [[
>   syntax off
>   filetype off
>   filetype plugin indent off
> ]]
> 
> vim.opt.shadafile = "NONE"
> vim.g.loaded_gzip = false
> vim.g.loaded_netrwPlugin = false
> -- you get the point
> 
> require "core"
> -- require things except plugins
> 
> vim.defer_fn(function()
>   require "plugins"
>   vim.opt.shadafile = ""
>   vim.cmd [[
>     rshada!
>     doautocmd BufRead
>     syntax on
>     filetype on
>     filetype plugin indent on
>     PackerLoad nvim-treesitter
>   ]]
>   vim.defer_fn(function()
>     vim.cmd [[
>       PackerLoad plenary.nvim
>       PackerLoad popup.nvim
>       PackerLoad which-key.nvim
>       PackerLoad nvim-lspconfig
>       -- PackerLoad other stuff
>       silent! bufdo e
>     ]]
>   end, 15)
> end, 0)
> ```

I did A LOT of testing with that in my own config a while ago, my conclusion was that it's not worth at all to do that nonsense.

1. You're just faking the profiler. It doesn't actually improve startup time and in fact, it gets worse. I benchmarked with external programs like hyperfine.  In my testing, while doing all the `vim.defer` does shows that the startup time apparently reduces when running with `--startuptime`. The truth was that it felt slower and this was even more obvious when testing with external tools like hyperfine. 

Here the average I got when using something like `vim.defer` and disabling all  of the shada files, syntax... To then just to re-enable them again.  

```
    Benchmark #1: nvim +q
        Time (mean ± σ):      87.3 ms ±   5.3 ms    [User: 71.0 ms, System: 14.0 ms]
        Range (min … max):    79.6 ms … 102.2 ms    45 runs
```

Here the average when NOT doing any of the very hacky tricks just to show a lower number in the startup time.

```
    Benchmark #1: nvim +q
      Time (mean ± σ):      66.2 ms ±   1.8 ms    [User: 50.3 ms, System: 12.7 ms]
      Range (min … max):    61.7 ms …  69.7 ms    45 runs

```

2. Besides all the numbers, the whole thing of disabling shada files, syntax, file type plugin, and more. Makes neovim feel slower (even if the startuptime says otherwise) than when not doing any of that. The reason is that at startup, there is no syntax highlighting, no colors, no nothing. And there's a delay before all of that gets activated again, and let tell me you that that delay is very noticeable when opening files, etc... by the other hand, when you're not doing any of that, it all happens instantly, no delay for the syntax to get activated when opening a file for example, hence it feels faster. 

So, I recommend not putting any of that in LunarVim, it's not worth doing all of those very hacky tricks just to show a lower startup time number (which as I said, you're just faking the profiler). The consequence is that the user experience is going to be worse because of the delay for the syntax highlighting and more to get activated. 

I haven't test the plugins that @ashincoder mentioned though, I'm gonna guess that lazy.nvim can actually help with startup time since it's from TJ himself. So if you want to improve startup time, either reduce the amount of plugins that come by default or try one of the alternatives that @ashincoder mentioned to see how much they can help. But doing all of the disable shada, syntax, file type, etc... just to re-enable them later and using the whole vim.defer function is definitely not worth it.

**Comment by ashincoder** [comment]
Maybe the plugins I mentioned can decrease the startuptime. And also what about some function to load plugins after loading the UI. Since it won't interfere with the startup processess.

**Comment by chase** [comment]
impatient.nvim requires very little work to introduce and is fundamentally different from lazy loading approaches. It requires very little configuration overall and [the benchmarks seem to show a significant decrease in loading time for modules used in LunarVim](https://github.com/lewis6991/impatient.nvim#performance-example)

What impatient.nvim seems to do is preload a cached version of Lua modules in a packed format so they can be loaded into Neovim without going through the parse step.

**Comment by ashincoder** [comment]
And also mpack is a luarock dep required for impatient.nvim. So there is a PR on making mpack as a dep for neovim.
check the below PR's of neovim to understand:
https://github.com/neovim/neovim/pull/15436
https://github.com/neovim/neovim/issues/15452

**Comment by chase** [comment]
I couldn't get Packer's `rocks` config to work as expected, so I had to install mpack after install luarocks, but I did get `impatient.nvim` working.

Before `impatient.nvim`:
```
  Config for telescope.nvim took 12.195517ms
  Config for lualine.nvim took 2.410065ms
  Config for nvim-colorizer.lua took 2.044322ms
  Config for nvim-treesitter took 0.786134ms
  Config for project.nvim took 0.623615ms
  Config for nvim-tree.lua took 0.458629ms
  Config for everforest took 0.026755ms
  Defining lazy-load keymaps took 0.020194ms
  Defining lazy-load event autocommands took 0.013366ms
  Defining lazy-load commands took 0.01069ms
  Defining packer_plugins took 0.004534ms
  Luarocks path setup took 0.001984ms
  try_loadstring definition took 0.000109ms
  ```

After:
```
  Config for telescope.nvim took 2.156299ms
  Config for nvim-colorizer.lua took 0.97987ms
  Config for nvim-treesitter took 0.690761ms
  Config for lualine.nvim took 0.386935ms
  Config for project.nvim took 0.167576ms
  Config for nvim-tree.lua took 0.070149ms
  Defining lazy-load keymaps took 0.018041ms
  Config for everforest took 0.017733ms
  Defining lazy-load event autocommands took 0.015164ms
  Defining lazy-load commands took 0.009703ms
  Defining packer_plugins took 0.004401ms
  Luarocks path setup took 0.00158ms
  try_loadstring definition took 0.000104ms
  ```

**Comment by ashincoder** [comment]
Me too. I had some issues setting up packer. https://github.com/lewis6991/impatient.nvim/issues/2

**Comment by ashincoder** [comment]
It is nice pretty fast. Maybe doing some more lazyloading in Lunarvim will improve
