### ISSUE TITLE
[Bug] Null-ls builtins command and name don't always match

### ISSUE THREAD

**Issue by Tastyep** [LunarVim/LunarVim#1454]
As we use the builtin's command to index `null-ls`'s builtins, it won't be found if command and name mismatch.
Example:
- https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting.lua#L65
- https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting.lua#L86
- https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting.lua#L97
- https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting.lua#L217
- ....

Either we make a static mapping on our side or upstream the change.
IMO it's probably more appropriate to maintain a mapping on our side.

**Comment by jose-elias-alvarez** [comment]
Is this still an issue? In [this commit](https://github.com/jose-elias-alvarez/null-ls.nvim/commit/378e5138a5accda963103e9864fab02b95ab1512) I changed it so that built-in names will default to the command (unless otherwise specified). I don't have a strong opinion on this either way, so I'm happy to make whatever changes make things easier here.

**Comment by Tastyep** [comment]
The problem is that we don't find the builtins by name:

**Comment by jose-elias-alvarez** [comment]
Ah, I see, I misunderstood then. Let me know if there's anything we can change on the null-ls side, then.

**Comment by kylo252** [comment]
Closing since the info here is outdated.
