### ISSUE TITLE
[Feature]: improve lvim.lang structure

### ISSUE THREAD

**Issue by kylo252** [LunarVim/LunarVim#1579]
# Description

Currently all the supported languages are stored in a single global table that gets passed around often. This  treatment of global `lvim.lang` as a in memory database is not the best of practices, both security and performance wise.

---

TODO: 
- [ ] break out the table into separate entries into the ftplugin file for each respective language
- [ ] switch to https://github.com/williamboman/nvim-lsp-installer to avoid hard-coding the paths of language servers
- [ ] create a config entry for supported languages to be used as fixed list [optional]
- [ ] remove null-ls autocompletion hints to save on memory [optional]
- [ ] autogenerate ftplugin files for certain problematic languages [optional]

**Comment by Tastyep** [comment]
About the first point, I have a stash on 1406 which contains these changes, I can't share it since it's based on other commits.
I can say that it works without issues, and it makes the rest of the config less heavy to read.
I think however that it would break autocompletion for `lang` entries, supposing that `ftplugin` files are evaluated after.
