### ISSUE TITLE
Overriding ttimeoutlen nvim default

### ISSUE THREAD

**Issue by 14mth3w0r5t** [LunarVim/LunarVim#1582]
Here you set ttimeoutlen
https://github.com/LunarVim/LunarVim/blob/65392c553ea6a69053a99fea57c3dee6c48afa75/lua/config/settings.lua#L28
while the default value is 50 [here](https://neovim.io/doc/user/options.html#'ttimeoutlen') (instead of 100, which I think will be a little slower)

I want if possible to know what the purpose of this

**Comment by rebuilt** [comment]
The default timeoutlen is 1000ms  (1 second).  You can prove this by launching vim or nvim with no configuration file.  
`nvim -u NONE`
And then check the default timeoutlen
`:set timeoutlen?`  

The timeoutlen is `Time in milliseconds to wait for a mapped sequence to complete.`

In practice this means that if `s` only does one thing.  It will run the action immediately.  But if you have a keymap for `ss`.  A single press of `s` no longer happens immediately.  It has to wait `timeoutlen` to figure out which action to take.  

The reason LunarVim lowers the timeoutlen from 1000 to 100ms is for the perceived performance of which-key.  Which-key waits `timeoutlen` to open.  Keeping it at default means you have to wait a full second for whichkey to open.  This makes it feel slow or laggy.  

You don't actually need the which-key menu to be visible for the action to trigger.  I personally set my timeoutlen at the default 1000 because I never want the whichkey menu to pop up unless I forget my keybindings.
