### ISSUE TITLE
[Bug]: null_ls selection tsserver on write

### ISSUE THREAD

**Issue by jeffrey-l-turner** [LunarVim/LunarVim#1607]
### Problem description

Use default configuration and `LspInstall typescript`.
Open `.ts` or `.tsx` file and then write it
Note conflict between:

![Screen Shot 2021-09-23 at 21 47 02](https://user-images.githubusercontent.com/1573697/134619709-0224c24f-a055-48fb-81d8-b13b523048ad.jpg)

I've dug through the code but can't find out why it asks to associate a server. This may ultimately be a `neovim` issue. I'm using the `rolling` branch currently

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

LuaJIT 2.1.0-beta3

### Neovim version (>= 0.5)

v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
you have format_on_save enabled, ( which is the default )
and when you try to save, lunarvim wants to format your code, but the issue is that tsserver doesn't support native formatting
<img width="999" alt="Screen Shot 2021-09-24 at 11 13 41 AM" src="https://user-images.githubusercontent.com/10992695/134637597-42f4801c-e6d2-4a4e-9f12-f8227961f806.png">
you can set `prettier` as your formatter for typescript and typescriptreact files
```lua
lvim.lang.typescript.formatters = { { exe = "prettier"  } }
lvim.lang.typescriptreact.formatters = { { exe = "prettier"  } }
```

**Comment by jeffrey-l-turner** [comment]
Although I hate prettier, that works. Thanks

**Comment by abzcoding** [comment]
😅 you can choose any of the other ones mentioned in that hint
