### ISSUE TITLE
[Feature]: Enable github discussion for this repository

### ISSUE THREAD

**Issue by mandaputtra** [LunarVim/LunarVim#1675]
### Feature motivation

Sometimes an issue are not an issue, sometimes I just want to aks something. Discord, Matrix, etc doesn't have a good way to track Q&A but github discussion does. so why not enable it?

### Describe the expected solution

Enabling Github Discussion

**Comment by chase** [comment]
I agree. We get a lot of Q&A in Discord that gets repeated all the time and it's nigh impossible to quickly just quote answers that have been asked recently but not within the past couple of hours.
The FAQ on the official site has a large barrier to entry, since it requires a PR to change and requires approval, so users can't contribute as they can on Discord.

**Comment by mandaputtra** [comment]
Yup adding more maintaner to docs site are good idea too. I want to help the docs, but I only follow the development on weekend so I miss a lot of update and decission.

If it is okay, the maintainer could add me to maintain the docs repo, as I'm rolling user I think I can add some FAQ and guides.

And I think this problem are a good problem, this mean that Lunarvim are growing big and more people choose to use it ❤️🚀

**Comment by chase** [comment]
It looks like Discussions are open! This can probably be closed
