### ISSUE TITLE
[Feature]: Vala LSP support

### ISSUE THREAD

**Issue by TheNightmanCodeth** [LunarVim/LunarVim#1779]
### Feature motivation

I write apps for GTK using Vala. There is a vala-ls config in nvim-lsconfig repo, but I don't know how to use it or add support. I've spent the last hour or so digging through different ways to add LSP support to nvim but I just can't wrap my head around it. I am new to nvim and nvim plugins in general, otherwise I'd put it together myself. 

### Describe the expected solution

create config files for [vala-language-server](https://github.com/Prince781/vala-language-server)

### Describe the alternatives you've considered

I've tried using coc to add the language server to neovim itself, but i simply couldn't figure out how to create the installer or config files.

**Comment by abzcoding** [comment]
if you have the time for it, you can contribute to https://github.com/williamboman/nvim-lsp-installer

so that everyone can enjoy the erlang lang server, here is a full example https://github.com/williamboman/nvim-lsp-installer/blob/main/CUSTOM_SERVERS.md#full-example

and also a sample of adding solang lang server https://github.com/williamboman/nvim-lsp-installer/pull/125

also the possible configurations for valals https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#vala_ls
