### ISSUE TITLE
[Bug]: Pyright doesn't autocomplete opencv

### ISSUE THREAD

**Issue by PBird** [LunarVim/LunarVim#1788]
### Problem description

I wrote simple code with opencv library. Lsp does not recognize opencv members. And gives me error. 

![image](https://user-images.githubusercontent.com/9611415/137588757-e024a16c-d974-4720-bcf8-3d417573223e.png)

![image](https://user-images.githubusercontent.com/9611415/137588827-61ea9c98-dd55-4a44-a996-36f83ae73f14.png)

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5.1

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
as mentioned in these, this is not a lunarvim issue,  The reason is that cv2 is not implemented in python and there is no source code to parse.


https://github.com/microsoft/pyright/issues/1461
https://github.com/microsoft/pyright/issues/1461
https://github.com/microsoft/pylance-release/issues/138
https://github.com/opencv/opencv/issues/14590

**Comment by abzcoding** [comment]
yeah, it seems like vscode is auto generating those somehow,
the same issue exists in coc as well -> https://github.com/fannheyward/coc-pyright/issues/378

**Comment by abzcoding** [comment]
or this 
https://github.com/microsoft/python-type-stubs
