### ISSUE TITLE
[Feature]: Support yarn3 and  plug n play for eslint and prettier

### ISSUE THREAD

**Issue by torkelo** [LunarVim/LunarVim#1938]
### Feature motivation

The way prettier and eslint are looked up from node_modules does not work with latest yarn 3 and plug and play.
https://yarnpkg.com/features/pnp 

Here is how it works today where it looks for binary in the node_modules/.bin folder that does not exist in yarn 3. 
https://github.com/LunarVim/LunarVim/blob/52b74557415eb757ad4b7481b0aec8a3f98dd58d/lua/lvim/lsp/null-ls/services.lua#L15 

### Describe the expected solution

* For it to just work with yarn3 and plug n play
* Or have a custom option to run prettier via "yarn prettier" or similar custom command

**Comment by chase** [comment]
I feel like this is far too specific of a case to support.

Have you tried setting the commands for null-ls directly?

**Comment by torkelo** [comment]
@chase 

> I feel like this is far too specific of a case to support. 

I think yarn3 and pnp will become very popular as it's so much faster than anything else (normal npm / yarn1) 

> Have you tried setting the commands for null-ls directly?

yes I have, I tried setting the command exe to "yarn prettier" but I get an error as it tries to execute `./node_modules/.bin/yarn prettier`  which does not exist

**Comment by chase** [comment]
> @chase
> 
> > I feel like this is far too specific of a case to support.
> 
> I think yarn3 and pnp will become very popular as it's so much faster than anything else (normal npm / yarn1)
> 
> > Have you tried setting the commands for null-ls directly?
> 
> yes I have, I tried setting the command exe to "yarn prettier" but I get an error as it tries to execute `./node_modules/.bin/yarn prettier` which does not exist

It isn't a tool that's well supported nor ubiquitous, likely because it requires significant tooling changes

What you need to do is register prettier with null-ls directly, not with lvim.
Set `command = "yarn"` and set `args = { "prettier", "$FILENAME" }`

Similarly, check out `eslint`'s default config and derive what you need for the args

Relevant documentation and files:
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#using-built-in-sources
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#eslint
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#prettier
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/eslint.lua
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/prettier.lua

**Comment by torkelo** [comment]
> It isn't a tool that's well supported nor ubiquitous

yarn3 is quite new I agree, but It is pretty well supported, (VSCode, webstorm, vim etc). Only issue was path to prettier/eslint. 

> What you need to do is register prettier with null-ls directly, not with lvim.
> Set command = "yarn" and set args = { "prettier", "$FILENAME" }

Where can I find example of that, checked the links you posted but could not figure it out. Do I need to unregister it with lvim? 

Can I do something like this in config.lua? 

```lua
local null_ls = require("null-ls")

local sources = {
    null_ls.builtins.formatting.prettier.with({
       command = "yarn"
       args = { "prettier", "$FILENAME" }
    }),
}

null_ls.config({ sources = sources })
````
 ?

**Comment by torkelo** [comment]
that actually partially worked, but the prettier write happens after save and only to the buffer so every time I save I end up with a modified buffer (and prettier errors in the webpack console).

**Comment by chase** [comment]
> yarn3 is quite new I agree, but It is pretty well supported, (VSCode, webstorm, vim etc). Only issue was path to prettier/eslint.

yarn pnp has been around for some time, even back to yarn 2, but it's fundamentally incompatible with anything that expects a standard node_modules-based ecosystem and requires an adapter to allow use by anything.

If you feel strongly that it should be supported, I would recommend pushing up a PR to simply override the command and args passed to the lvim-based setup.

`npm i -g prettier` _should_ work, because it should be in your path at that point: https://github.com/LunarVim/LunarVim/blob/52b74557415eb757ad4b7481b0aec8a3f98dd58d/lua/lvim/lsp/null-ls/services.lua#L42-L45

> that actually partially worked, but the prettier write happens after save and only to the buffer so every time I save I end up with a modified buffer (and prettier syntax errors in the webpack console as the file saved to disk did not get formatted).

That sounds like expected behavior for this default:
`lvim.format_on_save = true`

Disable it by setting it to false.
You can manually format the file by using `<leader>lf`

**Comment by torkelo** [comment]
Thanks! 

> That sounds like expected behavior for this default:

That is strange, not how any other editor handles format on save, formatting usually happens before save, not after. 

So setting 
> lvim.format_on_save = false

Will format before save? That is very confusing. I would assume format on save would format it then save it.

**Comment by chase** [comment]
> That is strange, not how any other editor handles format on save, formatting usually happens before save, not after (so the formatted file is saved)

Format-on-save with null-ls is more or less a hack, all things considered. You're welcome to improve things.

I personally disable it because it isn't context aware like proper language server support and causes cursor jumps quite often with prettier on a tight max line width.

> 
> So setting
> 
> > lvim.format_on_save = false
> 
> Will format before save? That is very confusing. I would assume format on save would format it then save it.

Incorrect. It will not format before save, just that null-ls support isn't great and format-on-save misbehaves in many cases, such as yours. As I said, setting it to `false` will *disable* formatting on save, as one would expect.

I recommended you manually format since it misbehaves.

You can also setup an autocommand to do what you want using the BufWritePre: https://www.lunarvim.org/configuration/05-autocommands.html

Something like:
```
lvim.autocommands.custom_groups = {
   { "BufWritePre", "*.ts", "silent !yarn prettier %" },
}
```

**Comment by torkelo** [comment]
thanks for all the help! 

I tried 
```
lvim.autocommands.custom_groups = {
   { "BufWritePre", "*.ts", "silent !yarn prettier %" },
}
```

but it's not working, if I remove the silent it does execute and print the formatted file but the buffer/file does not get updated

**Comment by chase** [comment]
> but it's not working, if I remove the silent it does execute and print the formatted file but the buffer/file does not get updated

`silent` just hides the output every write, as the name implies, it still runs.

That's just an example to get you started with using an autocommand, I highly recommend you Google the problem you're encountering to arrive at a solution for cases like this and use the built-in help. `:help autoread`, `:help edit`

**Comment by chase** [comment]
@torkelo I'll admit, I don't know `prettier` very well so my initial guidance wasn't on point. I spent a little more time on your issue and got this working (without the autocommand):

``` lua
local nullls_ok, nls = pcall(require, "null-ls")
if nullls_ok then
  nls.config {
    debug = true,
    debounce = 150,
    save_after_format = false,
    sources = {
      nls.builtins.formatting.prettier.with({
        filetypes = { "javascript", "typescript", "javascriptreact", "typescriptreact" },
        command = "yarn",
        args = { "run", "-B", "prettier", "--stdin-filepath", "$FILENAME" }
      }),
    }
  }
end
```

You can debug if the format is functioning correctly using `:NullLsInfo` and opening the log file mentioned.
The `debug = true,` flag should be removed if everything seems to work.

Based on what others have said, I would recommend using `prettierd` by the way, the start time overhead is significant enough to block and hang the editor because of how save-before-format is setup.

**Comment by torkelo** [comment]
@chase thank you so much :heart:
