### ISSUE TITLE
[Bug]: keybindings are reset to default 

### ISSUE THREAD

**Issue by YanzhaoW** [LunarVim/LunarVim#1993]
### Problem description

1. update lunarvim to the latest version v0.6.1
2. in configuration file (config.lua), add following line:
```
lvim.keys.normal_mode={
  ["<leader>q"] = ":q<CR>",
}
```
3. save and execute the file by `:w` and `:so %`
4. type `:map <leader>q` and press ENTER
output: `n <Space>q     *  :q<CR>`
5. exit lunarvim and reenter the config.lua file
6.  type `:map <leader>q` and press ENTER
output: `n <Space>q     * <Cmd>q!<CR>`

As can be seen, the keybindings are reset to the default setting once lunarvim is restarted.

PS: I really don't like the default keybindings for `<leader>q`. It's very dangerous to quit an unsaved work. Please change it in future version. 

### LunarVim version

v0.6.1

### Neovim version (>= 0.5)

v0.5.1

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Uzaaft** [comment]
Could you try the following:
lvim.keys.normal_mode["<leader>q>"] = "<ESC>:q<CR>"

**Comment by YanzhaoW** [comment]
> Could you try the following:
> 
> ```
> lvim.keys.normal_mode["<leader>q>"] = "<ESC>:q<CR>"
> ```

no, it doesn't work. And actually all my customized keybindings do not work after I updated the lunarvim to the version 0.6.1.
These also include:
```
lvim.keys.insert_mode["<A-k>"] = nil
lvim.keys.insert_mode["<A-j>"] = nil
```

I checked the commits in version 0.6.1 and some keybinding configuration was actually changed. see 3a2d62ed2510ca05eb6ea87240a86df82338f5aa. Could this be the problem?

**Comment by Uzaaft** [comment]
You could just go ahead and use git bisect to test out your config with different commits of LunarVim.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chase** [comment]
@YanzhaoW Can you please try the rolling branch?

We've done quite some work since the last stable release to improve the behavior of keybindings:
https://github.com/LunarVim/LunarVim/pull/1965
https://github.com/LunarVim/LunarVim/pull/1942

Also, to prevent loss in the meantime, set this in your `config.lua`:
`vim.opt.confirm = true`
If you have unsaved changes, this will prompt you to save or discard your changes.

**Comment by kylo252** [comment]
Fixed in #1949

**Comment by cizordj** [comment]
Hi can you please help me solving this issue? My keybindings are being reset after opening the explorer and it's happening both in the rolling and the master branches.

Here is the relevant part of my configuration:
![lvim-bug](https://user-images.githubusercontent.com/32869222/158502026-f523f080-f45f-441d-aea3-15719b38d447.png)

I don't have any additional installed plugin and this is just the plain vanilla config file edited by me. I wish to use these keybindings to switch buffers as you can see in the commented-out code.

I've tried restarting lvim and running the clear-cache command:
:LvimCacheReset
I've also tried:
:LvimReload

# LunarVim Version
rolling-a5e5b50

# NeoVim Version
v0.6.1

**Comment by kylo252** [comment]
@cizordj, there is a bit of an unfortunate segmentation, but keymaps that are prefixed with `<leader>` are controlled by which-key which gets called after (this is necessary for various plugins to work).

We could probably add a check to filter-out any pre-defined keymaps, but the easiest would be if you just assign them differently, since there aren't that many of them. You can even re-assign the entire table, which is what I do personally, https://github.com/kylo252/lvim/blob/da3d97f9422056a14f771f082232bc225be5a0c0/lua/user/whichkey.lua#L1

**Comment by cizordj** [comment]
@kylo252 I've replaced the whole table as you said and now it seems to be working as expected, thank you so much for your help.
