### ISSUE TITLE
[Bug]: There is a problem updating lunarvim null-ls

### ISSUE THREAD

**Issue by Leiyi548** [LunarVim/LunarVim#2004]
### Problem description

When I update lunarvim, I will report an error when I start, which seems to be the problem with null-ls.

### LunarVim version

relase

### Neovim version (>= 0.5)

0.6.0 -dev+606-g120a88163

### Relevant log output

```shell
NVIM v0.6.0-dev+606-g120a88163
Build type: Release
LuaJIT 2.1.0-beta3
```

### Screenshots

![image](https://user-images.githubusercontent.com/76139422/143820286-5d34828d-845e-4774-90d4-62a99b889c9d.png)
![image](https://user-images.githubusercontent.com/76139422/143820324-c6d6df29-9431-461e-9d1c-c889b2e06248.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
Please switch to the rolling branch if you want the latest `null-ls` updates, otherwise it's supposed to be fine on master as long as you don't update any plugins manually.

**Comment by Leiyi548** [comment]
@kylo252 I'm in the rolling branch.

**Comment by Leiyi548** [comment]
@kylo252 I'm sorry I misdescribed it. I'm in the rolling branch.

**Comment by kylo252** [comment]
Can you try these steps:

1. `:LvimUpdate` 
2. restart lvim
3. `:PackerSync`

If that still doesn't work, please share your `config.lua`. Also make sure to update your neovim-nightly since there's a breaking change related to `DiagnosticsChanged` which will get triggered in `nvim-tree`.

I just tried a fresh install, and it's working fine for me, so it did with just upgrading. Although, I did have to upgrade Neovim.

**Comment by Leiyi548** [comment]
@kylo252  Thankyou Slove this Problem
