### ISSUE TITLE
Treesitter highlighter

### ISSUE THREAD

**Issue by pannet1** [LunarVim/LunarVim#2148]
### Problem description

Go to visual mode  by pressing v or selecting with mouse and highlight line(s)

### LunarVim version

21b4168

### Neovim version (>= 0.6)

NVIM v0.6.1 Build type: Release LuaJIT 2.0.5 Compiled by builduser  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Operating system/version

EOS

### Relevant log output

```shell
:checkhealth
Running healthchecks...                                        
Error detected while processing function health#check:         
line   33:                                                     
E684: list index out of range: 0                               
Press ENTER or type command to continue  

:messages
vim.lsp.diagnostic.get_all is deprecated. See :h deprecated    
Error detected while processing function health#check:         
line   33:                                                     
E684: list index out of range: 0      

:e $LUNARVIM_CACHE
```
does not autocomplete for me and forcing hangs
```


### Screenshot
![Peek](https://user-images.githubusercontent.com/12350276/148388245-440d83c5-1503-415e-a6e8-5569bbbf2876.gif)

**Comment by EdmundsEcho** [comment]
I'm getting precisely the same error message "line 33, list index out of range..." when I run `checkhealth`.  

I did not know how to pinpoint if it was the `treesitter` portion of the test that causes the whole script to fail, but nonetheless thought it helpful to report my experience.

I updated neovim and plugins to no avail (I'm using the latest development version because I'm using an M1 chip).

```
NVIM v0.7.0-dev+852-g3088ac71f
Build type: Release
LuaJIT 2.1.0-beta3
```

\- E

**Comment by kylo252** [comment]
Please run `:TSUpdate` and see if it fixes that. The `checkhealth` situation is pretty messy for treesitter, so I wouldn't put too much faith into it.

**Comment by pannet1** [comment]
I could not handle it, so moved to stable branch. sorry for not abing to help. you may close this ticket, if required.

**Comment by EdmundsEcho** [comment]
I found the issue.  The source of the issue was another plugin that did not return a checkhealth output in certain circumstances.   It caused all tests to fail to display/report.  I should have run the checkhealth test specifically for this plugin (`checkhealth <plugin>`) to have better represented the situation.  A fix described here solves the problem https://github.com/neovim/neovim/pull/17012.
