### ISSUE TITLE
NVIM v0.7.0 full compability

### ISSUE THREAD

**Issue by abzcoding** [LunarVim/LunarVim#2476]
### Feature Description

use the new nvim v0.7.0 features like
- vim.keymap
- filetype.lua
-  nvim_{add,del}_user_command
- ...

[more info](https://github.com/neovim/neovim/releases/tag/v0.7.0)

**Comment by abzcoding** [comment]
cc: @kylo252

**Comment by kylo252** [comment]
The easiest way forward would be to pin newer versions to v0.7+ in order to avoid having to maintain a lot of compat wrappers. 

I'm hoping the post-update hook could be used to pin the version 
https://github.com/LunarVim/LunarVim/blob/1154817c47d972288d5f4d22017235a767262669/lua/lvim/utils/hooks.lua#L52-L53


Keeping plugins updated, even on a pinned lunarvim, has been greatly simplified since https://github.com/LunarVim/LunarVim/pull/2351, it's possible to either: 
- unlock all core plugins
```sh
# set this somewhere before calling lvim
export LVIM_DEV_MODE=1
```
- or simply use a different snapshot (the default snapshot directory is in `$LUNARVIM_CACHE_DIR/snapshots`)
```vim
:PackerSnapshotRollback <custom-snapshot-name>
```

**Comment by kylo252** [comment]
> The easiest way forward would be to pin newer versions to v0.7+ in order to avoid having to maintain a lot of compat wrappers.

@abzcoding, here's a test branch for this functionality: https://github.com/LunarVim/LunarVim/commits/version-lock
running `:LvimUpdate` in that branch should switch to `1.1.3` automatically, unless you have `nvim-0.9+` 😄 

_Note: the version-lock branch is only for testing, and https://github.com/LunarVim/LunarVim/commit/014dd27844af50e1bd226cc9f2c8e4cb8d23b0fb can be merged as usual to rolling_

**Comment by abzcoding** [comment]
> > The easiest way forward would be to pin newer versions to v0.7+ in order to avoid having to maintain a lot of compat wrappers.
> 
> @abzcoding, here's a test branch for this functionality: https://github.com/LunarVim/LunarVim/commits/version-lock running `:LvimUpdate` in that branch should switch to `1.1.3` automatically, unless you have `nvim-0.9+` 😄
> 
> _Note: the version-lock branch is only for testing, and [014dd27](https://github.com/LunarVim/LunarVim/commit/014dd27844af50e1bd226cc9f2c8e4cb8d23b0fb) can be merged as usual to rolling_

fantastic 👍

**Comment by abzcoding** [comment]
[Breaking changes inbound (next few weeks) for lspconfig and neovim's language server client lsp](https://www.reddit.com/r/neovim/comments/u5si2w/breaking_changes_inbound_next_few_weeks_for/)
Hi all,
I know a lot of you like to ride the nightly, so I wanted to warn about some incoming breaking changes (next week or so). For a lot (most?) of you, you won't even notice.
lspconfig will only support 0.7 or newer


https://github.com/neovim/nvim-lspconfig/pull/1838
