### ISSUE TITLE
lvim.builtin.lualine.options.theme = 'foo' in config.lua doesnt work

### ISSUE THREAD

**Issue by nobodyatandnothing** [LunarVim/LunarVim#2615]
### Problem description

if vim.colorscheme = 'onedarker', theme is set to onedarker no matter what.
i would like to set it to 'auto' to change automatically with the colorscheme
https://www.lunarvim.org/configuration/06-statusline.html#theme

### LunarVim version

d868dc1

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

linux

### Relevant log output

```shell
upon inquiry
```

**Comment by abzcoding** [comment]
when you set `lvim.colorscheme = 'onedarker'` the lunarvim is supposed to use the onedarker theme, therefore the lualine will use the same theme as well, because of this code
https://github.com/LunarVim/LunarVim/blob/d868dc14fe04792fc989bb94592f3ba697edd692/lua/lvim/plugins.lua#L14-L24

if you want to use other themes then set `lvim.colorscheme` to something else and then change the lualine to either `auto` or whatever you want
