### ISSUE TITLE
Incorrect auto-indentation for brackets and text.

### ISSUE THREAD

**Issue by jmoloko** [LunarVim/LunarVim#2877]
### Problem description

**Incorrect auto-indentation for brackets and text.**
![](https://media.giphy.com/media/8siKLYPY2zHmNx7K3T/giphy.gif)

### LunarVim version

master-b04aefb

### Neovim version (>= 0.7.2)

v0.7.2-3

### Operating system/version

ArchLinux

### support info

LspInfo
LvimInfo

**Comment by rebuilt** [comment]
Add this to your config to disable treesitter indentation for your language

```lua
lvim.builtin.treesitter.indent = {
  disable = { " go" }  
}
```

This is a known issue with treesitter indentation:   https://github.com/nvim-treesitter/nvim-treesitter/issues/2583

As you can see with treesitter playground open, the first set of brackets creates an error node.  Even without looking at playground, you'll know there's a syntax error because LSP reports a syntax error in red.  Then when you correct the syntax error, the indent for the last bracket seems to align to the right place.  
 
![indent](https://user-images.githubusercontent.com/16025007/182864950-cc3efcf6-ddaa-4db1-8114-7ae4e19e9694.gif)

**Comment by jmoloko** [comment]
Thank you so much!
You saved me)))
