### ISSUE TITLE
TSServer code actions

### ISSUE THREAD

**Issue by ea244wmi** [LunarVim/LunarVim#2945]
### Feature Description

What's the best way to setup [tsserver code actions](https://github.com/typescript-language-server/typescript-language-server#workspace-commands-workspaceexecutecommand).

### Describe the alternatives you have considered

I tried to run `:lua vim.lsp.buf.code_action()` but it didn't open any list with actions.

**Comment by cpea2506** [comment]
Code actions should be enable by default after you've installed the server.

Maybe the line you run the `code_action` function do not provide any of action. Some plugins like `[nvim-lightbulb](https://github.com/kosayoda/nvim-lightbulb)` could help you detect when actions are available.

And more than that, you can press `<leader>la` instead of typing the whole `vim.lsp` thing by hand.
