### ISSUE TITLE
Lunar vim switches to last tab on window resize

### ISSUE THREAD

**Issue by jarbus** [LunarVim/LunarVim#3007]
### Problem description

Not sure if this is my machine only, but this happens with a default config. If you have multiple tabs open, when I resize lunarvim with something like a tiling window manager, it switches to the last tab, regardless of what tab it was previously on. This does not occur in regular nvim.

### LunarVim version

master-b04aefb

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

Arch Linux

### Steps to reproduce

1. Have two tabs open, ex: `lvim -p test1.txt test2.txt`
2. Make sure you have `test1.txt` selected
3. Resize the window with a tiling window manager
4. Lvim switches to selecting test2.txt

### support info

```console
:LvimInfo
Error executing Lua callback: vim/shared.lua:0: t: expected table, got nil                                
stack traceback:                                                                                          
        [C]: in function 'error'                                                                          
        vim/shared.lua: in function 'validate'                                                            
        vim/shared.lua: in function <vim/shared.lua:0>                                                    
        vim/shared.lua: in function 'tbl_filter'                                                          
        ...e/jack/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:115: in function 'make_auto_lsp_info' 
        ...e/jack/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:159: in function 'toggle_popup'       
        ...ck/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:29: in function <...ck/.local/share/lu
narvim/lvim/lua/lvim/core/commands.lua:28> 
```

**Comment by lvimuser** [comment]
Does it happen on rolling?

**Comment by jarbus** [comment]
This issue is not stale :(

**Comment by Isti115** [comment]
Based on https://github.com/akinsho/bufferline.nvim/issues/409 this happens due to this autocommand that's enabled by default:  
https://github.com/LunarVim/LunarVim/blob/master/lua/lvim/core/autocmds.lua#L82

If I understand correctly, it executes window equalization (_which I also don't like / need_) on all tabs, which means that it switches through all of them and lands on the last one.

I was able to get rid of the issue (and window normalization as well) by deleting the group, to which the autocommand belongs:
`vim.api.nvim_del_augroup_by_name('_auto_resize')`

(I've placed this at the end of my `config.lua`.)

**Comment by jarbus** [comment]
Thank you so much! I need to start looking at issues for the plugins as well as just lvim when diagnosing bugs.

**Comment by dylan-chong** [comment]
since this is still a bug, we should still leave this open
