### ISSUE TITLE
[Hacktoberfest] aggregate all icons to one file and use throughout config

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#3092]
All icons should be scoped to one file named correctly and referenced throughout the config.

The icons should also be overrideable.

Similar to this file: https://github.com/ChristianChiarulli/lvim/blob/master/lua/user/icons.lua

**Comment by prichrd** [comment]
Hey @ChristianChiarulli , can I work on this as part of Hacktoberfest?

**Comment by ChristianChiarulli** [comment]
@prichrd yup!

**Comment by prichrd** [comment]
@ChristianChiarulli, does it make sense to have the icons file at the `lua/lvim/` level (e.g. `lua/lvim/icons.lua`)? 
I'd add them with default values and import `lvim.icons` everywhere in core where it is needed. For configuration, I'll probably do something similar to keymaps.

**Comment by ChristianChiarulli** [comment]
@prichrd yea I think putting them in `lual/lvim/icons.lua` is a good idea

**Comment by prichrd** [comment]
Hey @ChristianChiarulli, I have familiarised myself with the code, and I am hitting a little problem.

Aggregating the icons to one file is not problematic; making them overrideable via the `config.lua` file will require more thinking. The current flow for loading configurations is:
1. Load default configs
2. Load builtins configs (containing icons in the case of alpha, for instance)
3. Load user-defined configs `config.lua` (cannot override strings generated by builtins config)

I thought of a solution but wanted to run it by you before jumping in. What if we had user-defined config file for "theme" based configs (e.g. `theme.lua`) that would contain color-schemes configs, borders (#3105), icons, etc. That would allow us to load the default and user-defined theme configs before configuring the plugins. It would not change the default behaviour of the `config.lua` file because users could still override the builtin configs.

Any thoughts?

**Comment by ChristianChiarulli** [comment]
@prichrd you're kinda bumping up against my number 1 issue with lunarvim at this point which is how can I best provide a default experience and have the user override specific settings in an intuitive way. I guess we can take out the user overrideable AC for now. We can add another issue for that.
