### ISSUE TITLE
When I have error in config file so many pop window make me blind to vim how to limit the error popup window? 

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3265]
![image](https://user-images.githubusercontent.com/11295355/196036775-38748fd1-d9b2-43d4-8f9e-ab3d1f09bea6.png)

![image](https://user-images.githubusercontent.com/11295355/196036860-9a082ae6-d301-4bf9-8473-ac6dcacc6e1d.png)

You can see the in the picture. I have to wait about 5 secs until the popup window dismissed. How to make it just popup one window a time

**Comment by abzcoding** [comment]
either just disable it
```lua
lvim.builtin.notify.active = false
```
or configure it
```lua
lvim.builtin.notify.opts.<sth> = <someotherthing>
```

more info 
1. their repo -> https://github.com/rcarriga/nvim-notify
2. our default config -> https://github.com/LunarVim/LunarVim/blob/7715900525e5cfd7b210f9de8dd2fb25fe37b512/lua/lvim/core/notify.lua#L8

**Comment by LostNeophyte** [comment]
https://github.com/rcarriga/nvim-notify/issues/120#issuecomment-1214168883

**Comment by chase** [comment]
I believe this is caused by multiple instances of nvim-notify's hooks being loaded after the config is reloaded. I've noticed this behavior only after modifying my config and it seems that if you do 4 successful saves, it does ~`2^(4 - 1)` of the same notification if the config load is a failure. This makes it seem like on reload the old value of the hook is stored and called.
