### ISSUE TITLE
remove nvim-notify from the core plugins

### ISSUE THREAD

**Issue by kylo252** [LunarVim/LunarVim#3294]
Unfortunately, [nvim-notify](https://github.com/rcarriga/nvim-notify) has been causing way too many issues and instabilities.

several plugins are now using `vim.notify` notice that would trigger in the middle of packer's operations, at that point `nvim-notify` lost its state or something, and you get crazy errors like this

<details>
<summary>expand</summary>

```gdb
Error executing vim.schedule lua callback: ...ker/start/nvim-notify/lua/notify/serv
ice/buffer/init.lua:98: Vim(set):E474: Invalid argument: colorcolumn=value
stack traceback:
        [C]: in function 'nvim_buf_set_option'
        ...ker/start/nvim-notify/lua/notify/service/buffer/init.lua:98: in function 'render'
        ...ack/packer/start/nvim-notify/lua/notify/service/init.lua:53: in function 'push'
        ...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:209: in function 'impl'
        ...start/structlog.nvim/lua/structlog/sinks/nvim_notify.lua:49: in function 'write'
        ...ack/packer/start/structlog.nvim/lua/structlog/logger.lua:58: in function 'log'
        ...ack/packer/start/structlog.nvim/lua/structlog/logger.lua:64: in function 'log'
        ...cedraz-/.local/share/lunarvim/lvim/lua/lvim/core/log.lua:155: in function 'add_entry'
        ...cedraz-/.local/share/lunarvim/lvim/lua/lvim/core/log.lua:198: in function 'info'
        ...raz-/.local/share/lunarvim/lvim/lua/lvim/utils/hooks.lua:22: in function 'run_on_packer_comp
lete'
        ...z-/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:50: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

```

</details>

it feels like so many plugins are spamming `vim.notify` to the point where it's hard to keep track of all of these popups.. :disappointed:  

also, we've had to create sketchy workarounds just for the sake of having this plugin

<details>
<summary>expand</summary>

https://github.com/LunarVim/LunarVim/blob/c015d0feeed35b34d84558a8e4a49549b3b67781/lua/lvim/core/nvimtree.lua#L155-L166

</details>

here are some related issues and complaints I've managed to find
- https://github.com/LunarVim/LunarVim/issues/3265
- https://github.com/LunarVim/LunarVim/issues/2713
- https://github.com/LunarVim/LunarVim/issues/2242
- https://github.com/LunarVim/LunarVim/issues/1821
- https://github.com/LunarVim/LunarVim/issues/2778
- https://github.com/LunarVim/LunarVim/issues/2960
- https://github.com/LunarVim/LunarVim/issues/2734
- https://github.com/LunarVim/LunarVim/issues/2738
- https://github.com/LunarVim/LunarVim/issues/2673

**Comment by ChristianChiarulli** [comment]
I think we're all on the same page here

**Comment by danielo515** [comment]
Is there a way to call it only on purpose and avoid it hijacking the vim.notify method? I think showing nice errors, warnings and useful information in nice notifications is often useful. For example when using deprecated functionalities or as a response to empty search results, etc.

**Comment by kobzar** [comment]
Really the VIM users doesn't need this notification. Its no vim like way. 
Usually we are working with command promt for all of our task. I mean search/replace text, run some commands like :lvimupdate etc.
The next one we`re use wichkey plugin like SPS+ look on the variants if forget something hotkey or SPS + L +k to find them. 
So, really - the notification plugin isn`t needed. 
If we have the error or some informative message - just show it on the bottop window place area  as the all information for any VIM  news.
The next one - we can use short messages and somethon like Telescope, fzf e.tc to show full message list to copy/analyze it. 

For myself notyfi is ugly, for example i change configuration or do something strange and i catch short wrap message with info for short time - and next i must found who write this message, where is full message and so on.

**Comment by danielo515** [comment]
> Really the VIM users doesn't need this notification. Its no vim like way.

I'm not saying this plugin is not intrusive, but "Its no vim way" argument should not be used to argue against or in favour of any feature. People don't come to Lunarvim looking for a tipical vim experience. Many people, myself included, like the VSCode/Ide feeling it has, while vim is just a text-editor.
On top of that, there is no "vim way". That is a construct each user has in their minds, and you may feel there is an unified way of doing things ala vim, but each individual has its own perception of this.

The reason why I like the notifications is because it's not comfortable for me to look at the bottom of the screen every-time there is a little message. Most of the times I don't know what is happening, why my keyboard is not doing what I am telling it to do until I see there is a prompt in the bottom of the screen. Also, with vim-notify at least I have an easy way to access the history of notifications, this is not as easy with the bottom bar, since the `:messages` is usually very abused and is full of other irrelevant stuff.

**Comment by kobzar** [comment]
VIM is freedom. 
Yes, i cant understand anyone who try to make VSCode from VIM. But its normaly. 
Thats why we are love the vim - because you can cook what you want.
We are speak about remove this plugin from Core plugins. Everyone and everytime can use it but for their own risk, like any external plugin.

**Comment by danielo515** [comment]
> VIM is freedom.

Yes, that was my point.



> We are speak about remove this plugin from Core plugins. Everyone and everytime can use it but for their own risk, like any external plugin.

Yes, and my point is around the default user experience. I think that having the ability to show notification toasts from the LunarVim core, it's a nice thing to have.
That said, removing this plugin will probably do more good than harm, and we can always add a better notification system under our control.

Regards

**Comment by spacerodent** [comment]
> The reason why I like the notifications is because it's not comfortable for me to look at the bottom of the screen every-time there is a little message. Most of the times I don't know what is happening, why my keyboard is not doing what I am telling it to do until I see there is a prompt in the bottom of the screen. Also, with vim-notify at least I have an easy way to access the history of notifications, this is not as easy with the bottom bar, since the `:messages` is usually very abused and is full of other irrelevant stuff.

I agree. I love the pop ups.

**Comment by marcopiraccini** [comment]
Tnx for this. It was really annoying :)
