### ISSUE TITLE
LvimUpdate gives too little feedback

### ISSUE THREAD

**Issue by LostNeophyte** [LunarVim/LunarVim#3377]
### Problem description

when you run  :LvimUpdate and have the latest version there's no feedback
there's also no feedback before (potentially taking 5s) git fetch

### LunarVim version

master

### Neovim version (>= 0.8.0)

0.9

### Operating system/version

linux

### Steps to reproduce

run `:LvimUpdate`

### support info

none

**Comment by LostNeophyte** [comment]
It's warn by default

**Comment by LostNeophyte** [comment]
I thought it would be good to have feedback with the defaults

**Comment by kylo252** [comment]
> OK, but I think vim.schedule is still needed so the user doesn't need to wait for the command to finish for the first message

not sure I get the workflow here, isn't the other part of the issue solved as well with an appropriate log level? since this message _should_ be printed before any job is executed
https://github.com/LunarVim/LunarVim/blob/6ea5341a846e8bc1848ce765c6d97f1dbbd307d5/lua/lvim/utils/git.lua#L62

if it's not, we probably need to change this option instead
https://github.com/LunarVim/LunarVim/blob/6ea5341a846e8bc1848ce765c6d97f1dbbd307d5/lua/lvim/core/log.lua#L44

**Comment by LostNeophyte** [comment]
> > OK, but I think vim.schedule is still needed so the user doesn't need to wait for the command to finish for the first message
> 
> not sure I get the workflow here, isn't the other part of the issue solved as well with an appropriate log level? since this message _should_ be printed before any job is executed
> 
> https://github.com/LunarVim/LunarVim/blob/6ea5341a846e8bc1848ce765c6d97f1dbbd307d5/lua/lvim/utils/git.lua#L62
> 
> if it's not, we probably need to change this option instead
> 
> https://github.com/LunarVim/LunarVim/blob/6ea5341a846e8bc1848ce765c6d97f1dbbd307d5/lua/lvim/core/log.lua#L44

At least with vim.notify and  echo, the command needed to finish for any output to show. Will check without asynx tomorrow, I'm finishing for today

**Comment by LostNeophyte** [comment]
So, log doesn't show up before the git merge finishes regardless if async is set or not, even with vim.schedule. notify does
