### ISSUE TITLE
Icons should be overrideable

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#3383]

**Comment by LostNeophyte** [comment]
Didn't #3115 do that? Or do you mean different icons

**Comment by ChristianChiarulli** [comment]
@LostNeophyte I mean changing the icons, that just got them all in one place

**Comment by LostNeophyte** [comment]
> @LostNeophyte I mean changing the icons, that just got them all in one place

You can do this `lvim.icons.ui.Circle="o" ` for example

**Comment by ChristianChiarulli** [comment]
oh, I have no idea why that didn't work for me before, thanks @LostNeophyte

**Comment by ChristianChiarulli** [comment]
Actually it looks like some work and some don't, try overriding snippet for instance:

```
lvim.icons.kind.Snippet="s"
```

**Comment by LostNeophyte** [comment]
> Actually it looks like some work and some don't, try overriding snippet for instance:
> 
> ```
> lvim.icons.kind.Snippet="s"
> ```

where is snippet used?

**Comment by LostNeophyte** [comment]
works for me 
![image](https://user-images.githubusercontent.com/110467150/200129194-d4b202d9-6c7e-4b53-861d-67c08aca2792.png)

**Comment by ChristianChiarulli** [comment]
welp I guess I'm doing something stupid again

**Comment by LostNeophyte** [comment]
@ChristianChiarulli 

I know what's going on now,
```lua
lvim.icons.kind.Snippet="s" -- this works
lvim.icons = {...} -- cmp icons don't work
```
It's because [this](https://github.com/LunarVim/LunarVim/blob/f08a9972094e4c183fe93715e4de47126137647c/lua/lvim/core/cmp.lua#L154) runs before the user's config does and sets `kind_icons` in cmp to `lvim.icons.kind`, which in lua is by reference and so `lvim.icons.kind.Snippet = "s"` works, because the reference still points there, but if you do `lvim.icons = {...}`, cmp has reference to the old table
