### ISSUE TITLE
Error when editing a C# file. E5248: Invalid character in group name

### ISSUE THREAD

**Issue by DraxCodes** [LunarVim/LunarVim#3716]
### Problem description

Whenever I edit a csharp file, I receive the following message.
```bash
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:344: Vim(redraw):E5248: Invalid character in group name
stack traceback:
        [C]: in function 'nvim_command'
        /usr/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:344: in function 'process_response'
        /usr/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:269: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1391: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
 ```
 
 The project I was using was the generic console app template generated via the dotnet cli tools (`dotnet new console`).
 It only had the following code within it (as generated by the template)
 ```cs
 Console.WriteLine("Hello World");
 ```
 
The Error message pops up whenever I try to type anything into the window. (As shown below)

![LR4zP4](https://user-images.githubusercontent.com/1976592/212168264-e23a7c49-e73f-4d62-878c-906db29f5d6f.png)

### LunarVim version

Nightly

### Neovim version (>= 0.8.0)

v0.9.0-dev

### Operating system/version

Ubuntu 20

### Affected language servers

c-sharp

### Steps to reproduce

1. Create a new C# project using the dotnet tooling (`dotnet new console`)
2. Open the Program.cs file
3. Try to make any changes to the file such as adding a second Console.WriteLine.

### Actual behavior

Receive the error as described in the description above.

### Expected behavior

No errors, able to edit the Program.cs file.

### support info

![1ju7Pu](https://user-images.githubusercontent.com/1976592/212169468-0b084c8f-681e-4f63-9339-3803d2701ab4.png)
![9CTd8F](https://user-images.githubusercontent.com/1976592/212170010-ac6d88d2-b567-48f6-b27c-1abbdd2506c5.png)

**Comment by DraxCodes** [comment]
Of course. 
[TestConsole.zip](https://github.com/LunarVim/LunarVim/files/10414555/TestConsole.zip)

**Comment by kadencartwright** [comment]
I am having this issue in vanilla nvim using omnisharp as well. check out https://github.com/OmniSharp/omnisharp-roslyn/issues/2483. apparently something to do with semantic tokens ? looking for a workaround

**Comment by kadencartwright** [comment]
There is a workaround listed in the above issue where you can redefine the non conforming tokens manually, so that could be a valid fix temporarily. 

I'm playing around with a few options including using a different lang server than omnisharp, but I've had no luck yet.

Not sure if there was a specific reason omnisharp has drifted from the LSP spec, but that seems to be the root of the issue

**Comment by kadencartwright** [comment]
The other solution is to use 'csharp_ls' instead of omnisharp
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#csharp_ls .
I tried to poke around the lunarvim docs, but I'm not familiar enough with the config architecture. I think someone else will have to help with giving instructions on what the idiomatic way is to configure lvim to use 'csharp_ls' instead of omnisharp

**Comment by LostNeophyte** [comment]
thanks for the info @kadencartwright!

it's not a lunarvim issue in that case, it's weird that they don't implement the specification correctly 

> I think someone else will have to help with giving instructions on what the idiomatic way is to configure lvim to use 'csharp_ls' instead of omnisharp

It's in the docs [here](https://www.lunarvim.org/docs/languages#server-override), if the docs aren't clear please let me know, I'm actually currently working on refactoring them so I'll rewrite the lsp section if it's bad

**Comment by lopesivan** [comment]
https://nicolaiarocci.com/making-csharp-and-omnisharp-play-well-with-neovim/
