### ISSUE TITLE
Tabedit bug

### ISSUE THREAD

**Issue by cnshsliu** [LunarVim/LunarVim#3837]
### Problem description

1.   shell> lvim /tmp/1.txt
2. within lvim. :tabe /tmp/2.txt
3. then :tabe /tmp/3.txt
4. 2gt
5. :q

the first 3 steps will open /tmp/1.txt /tmp/2.txt /tmp/3.txt in three tabs
Step 4: 2gt will switch to /tmp/2.txt tab
Step 5: :q will close /tmp/2.txt

Then, you will see /tmp/2.txt tab still exist
1gt will goto /tmp/1.txt, but 2gt will goto /tmp/3.txt, not /tmp/2.txt

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Operating system/version

Ventura 13.1 (22C65)

### Steps to reproduce

with minimal config

The problem does not exist.

but with default installation, problem exists.

### Screenshots

<img width="475" alt="image" src="https://user-images.githubusercontent.com/2124836/218296125-4fcdde1d-9811-48f0-aba4-b07bcc395357.png">

**Comment by aniketgm** [comment]
This is because tabs are different from buffers. When you are in file /tmp/2.txt (tab 2), and do `:q`, It closes the respective tab and not the buffer. the buffer still exists. You can check this behavior in neovim too (nvim). To check all the buffers in a nvim session do `:ls` Or `:buffers!`

The tabs that you see above in lvim are not tabs but buffers. Tabs are shown on the right side top.
