### ISSUE TITLE
LvimUpdate Cannot update Lvim from v1.2.0 to v1.3.0

### ISSUE THREAD

**Issue by c02y** [LunarVim/LunarVim#4083]
### Problem description

Following instructions from https://www.lunarvim.org/docs/installation#updating-lunarvim, unable to update lvim from v1.2.0 to v1.3.0
- `:LvimUpdate`
- `lvim +LvimUpdate +q`

log:
```
>> lvim +LvimUpdate +q

00:08:11 [INFO ] lvim: "Checking for updates"         file="git.lua", line=62
00:08:13 [INFO ] lvim: "LunarVim is already up-to-date" file="git.lua", line=77⏎
```

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

neovim 0.8.3-1 or neovim v0.9.0

### Terminal name

Kitty or Alacritty

### Operating system/version

Arch Linux

### Steps to reproduce

- `LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh)`
- Do nothing to the config.lua
- edit `lvim.log.level = "info"` in ~/.config/lvim/config.lua
- `lvim +LvimUpdate +q` or `:LvimUpdate`

Nothing happens

```
>> lvim +LvimUpdate +q

00:08:11 [INFO ] lvim: "Checking for updates"         file="git.lua", line=62
00:08:13 [INFO ] lvim: "LunarVim is already up-to-date" file="git.lua", line=77⏎
```
```
:LvimUpdate
:message
00:17:17 [INFO ] lvim: "Trying to update LunarVim..." file="bootstrap.lua", line=117
00:17:17 [INFO ] lvim: "Checking for updates"         file="git.lua", line=62
00:17:18 [INFO ] lvim: "LunarVim is already up-to-date" file="git.lua", line=77
````

**Comment by nieomylnieja** [comment]
had the same issue, I ended up just reinstalling it with the new version, the update seemed to not have been doing anything at all

**Comment by LostNeophyte** [comment]
LvimUpdate doesn't change the branch, to update between the branches run the install command

**Comment by LostNeophyte** [comment]
this info should be in the docs though

**Comment by c02y** [comment]
Thanks, didn't know that.

**Comment by HamishPoole** [comment]
```
2023-04-27 11:47:53 [INFO ] lvim: "Trying to update LunarVim..." file="lvim/lua/lvim/bootstrap.lua", line=117
2023-04-27 11:47:53 [DEBUG] lvim: "Starting pre-update hook"     file="lua/lvim/utils/hooks.lua", line=8
2023-04-27 11:47:53 [INFO ] lvim: "Checking for updates"         file="lua/lvim/utils/git.lua", line=62
2023-04-27 11:47:53 [DEBUG] lvim: { "false" }                    file="lua/lvim/utils/git.lua", line=31
2023-04-27 11:47:54 [INFO ] lvim: "LunarVim is already up-to-date" file="lua/lvim/utils/git.lua", line=77
2023-04-27 11:48:08 [DEBUG] lvim: { "release-1.2/neovim-0.8" }   file="lua/lvim/utils/git.lua", line=31
2023-04-27 11:48:08 [DEBUG] lvim: { "8f4a7bde" }                 file="lua/lvim/utils/git.lua", line=31
```

Same issue.

> i'll keep the issue open for the docs enhancement

Wise response.

```
Updating LunarVim

    Inside LunarVim :LvimUpdate
    From the command-line lvim +LvimUpdate +q

Update the plugins

    Inside LunarVim :LvimSyncCorePlugins
 ```

`:LvimUpdate` performs very differently to expectations.

https://github.com/LunarVim/lunarvim.org/blob/master/versioned_docs/version-1.3/installation/installation.md

Happy to own this issue and update documentation.

@LostNeophyte 

Can you confirm the maintainers' *intended purpose* of `:LvimUpdate` is:

"Update LunarVim installation to latest commit of current release branch."

Understanding intent & goal is the key here.

**Comment by LostNeophyte** [comment]
> `:LvimUpdate` performs very differently to expectations.
> 
> https://github.com/LunarVim/lunarvim.org/blob/master/versioned_docs/version-1.3/installation/installation.md
> 
> Happy to own this issue and update documentation.

That'd be great, thank you

> 
> @LostNeophyte 
> 
> Can you confirm the maintainers' *intended purpose* of `:LvimUpdate` is:
> 
> "Update LunarVim installation to latest commit of current release branch."

Correct

**Comment by LostNeophyte** [comment]
it moves it to lvim.old, doesn't overwrite it, it says it in the output "Backing up old $src to $src.old"

**Comment by LostNeophyte** [comment]
> @LostNeophyte , I just checked it, it is not there.

~/.config/lvim.old doesn't exist?

> No matter, I'm moving on. Thanks.

it does matter to me, it's quite a big bug if the installer destroys the user's config

**Comment by c02y** [comment]
Luckily, I manually backed up all the nvim/lunarvim/lvim directories before executing the `LV_BRANCH='release-1.3/neovim-0.9 ...`  command.

**Comment by kobzar** [comment]
I don't understand the topic. 
We have a new project with lot of changes. The main of them is moved from one packages manager to another.
So, lvim 1.2 and lvim 1.3 is the different product.
Lvim it's no new editor. Its presets a lot of default nvim settings. 
This is strange to compare 1.2 and 1.3 release. 
Its couldn't be updatable by fact.
The same as libs for any Langs - you are just use instruments from selected version.
So, for my opinion, I don't see the future for this polemic.
Lvim is change kernel - so you must to reinstall - not upgrade.
maybe this will fixed in new releases but not now.
The same as linux - change the kernel not change the os release. 
But os release change the kernel.

**Comment by c02y** [comment]
> I don't understand the topic. We have a new project with lot of changes. The main of them is moved from one packages manager to another. So, lvim 1.2 and lvim 1.3 is the different product. Lvim it's no new editor. Its presets a lot of default nvim settings. This is strange to compare 1.2 and 1.3 release. Its couldn't be updatable by fact. The same as libs for any Langs - you are just use instruments from selected version. So, for my opinion, I don't see the future for this polemic. Lvim is change kernel - so you must to reinstall - not upgrade. maybe this will fixed in new releases but not now. The same as linux - change the kernel not change the os release. But os release change the kernel.

Understandable, so now the topic in later replies changes to doc should mention this about `LvimUpdate`.

**Comment by FlippingBinary** [comment]
I use git to track changes to my config and synchronize it between multiple computers. It seems that the update process destroyed my .git subdirectory, which caused me some extra frustration as I had to clone my old config again and move the new config directory out of the way before moving my old config in place. This disruptive replacement of my config took extra time and made me wonder if there might be a better way to handle updates. After all, I would expect most users who made meaningful changes to their config would just try their old config and integrate the new config changes into it rather than the other way around.

I would like to propose that instead of replacing the user's old configuration directory with a new one, an example configuration file be installed next to the user's customized configuration file as `config.v1.3.example.lua`. This way, users can refer to it easily and work through the changes that may be necessary. In fact, this example file could be installed even during initial installation so we have a default config to fall back on if we want. Right now I keep example options commented out rather than removing them entirely so I can easily refer to it later, so I probably should have done this myself, lol.

Additionally, I was wondering if it would be possible to have `:LvimUpdate` warn that there is a newer branch available to avoid confusion when a user of v1.2 sees their editor is the most recent version. 

Also, a separate option like `:LvimChangeBranch v1.3` that would enable a branch change in place would be much more convenient than the current method. Of course, that command would have to prompt for confirmation and warn that the old config may not be directly compatible and they should only do a branch change if they have the time to deal with it.

**Comment by LostNeophyte** [comment]
> I use git to track changes to my config and synchronize it between multiple computers. It seems that the update process destroyed my .git subdirectory, which caused me some extra frustration as I had to clone my old config again and move the new config directory out of the way before moving my old config in place. This disruptive replacement of my config took extra time and made me wonder if there might be a better way to handle updates. After all, I would expect most users who made meaningful changes to their config would just try their old config and integrate the new config changes into it rather than the other way around.

that's a bug, the update shouldn't delete your files, only move them. maybe it would be better if the installer just wouldn't back anything up, didn't delete cache and didn't delete the user's config

> Additionally, I was wondering if it would be possible to have :LvimUpdate warn that there is a newer branch available to avoid confusion when a user of v1.2 sees their editor is the most recent version.

we could change the "lvim is up to date" message to "you're on the latest patch of your version" or something like that, I'm not too keen on creating a function that would parse git output and check if a new branch exists, but it would improve UX so maybe, i'd need someone's from the team opinion on that

> Also, a separate option like :LvimChangeBranch v1.3 that would enable a branch change in place would be much more convenient than the current method. Of course, that command would have to prompt for confirmation and warn that the old config may not be directly compatible and they should only do a branch change if they have the time to deal with it.

I'm not sure if that's possible(i didn't think about it too hard though, i'm tired), it would probably need to run the installer and idk if a running neovim instance would conflict with it, it would be probably very problematic

---

I do agree that the current system is quite unintuitive, I'd love to solve it with packaging(we have untested appimage, deb, exe, ... releases which in my opinion are a way more convenient way to install software than shell scripts), but currently i don't have enough motivation for it, but i might work on it a bit next week.

as for the installer, maybe it just shouldn't backup anything and create a new example config if the user already has a config, the current behavior seems unnecessary to me

**Comment by FlippingBinary** [comment]
> we could change the "lvim is up to date" message to "you're on the latest patch of your version" or something like that, I'm not too keen on creating a function that would parse git output and check if a new branch exists, but it would improve UX so maybe, i'd need someone's from the team opinion on that

Changes to the legacy branches still get pulled in by `:LvimUpdate`, right? How about a little change to the "currently up-to-date" message on legacy branches that says "... but there is a new branch! Go to lunarvim.org for current installation instructions" or something like that. Then you don't need to parse git output to figure it out.

>I'm not sure if that's possible(i didn't think about it too hard though, i'm tired), it would probably need to run the installer and idk if a running neovim instance would conflict with it, it would be probably very problematic

It would not surprise me if a major change like this in an open instance of neovim would crash it. If I recall correctly, I had other instances of LunarVim running when I did my update and they stopped responding. But  I've got my fingers crossed.

**Comment by FlippingBinary** [comment]
Since writing the comments above, I tried updating LunarVim on my phone where it preserved the previous config directory correctly, including the `.git` subdirectory. I had thought the install script destroyed my `.git` subdirectory, but I now believe it might not have preserved my old config at all because I already had an `lvim.old` directory, which contained a version of my config from before I started using git. 

Sorry about the confusion.

**Comment by HamishPoole** [comment]
```I do agree that the current system is quite unintuitive, I'd love to solve it with packaging(we have untested appimage, deb, exe, ... releases which in my opinion are a way more convenient way to install software than shell scripts), but currently i don't have enough motivation for it, but i might work on it a bit next week.```

One (unwise) alternative I have seen is a script where LunarVim queries the GitHub.com git remote to get the latest release tag.  ...an option, not a good option.

Far better experience for everyone to distribute LunarVim via brew/apt/yarn really.

**Comment by FlippingBinary** [comment]
I think an in-place upgrade process might be possible, but I'm not familiar enough with lua and NeoVim internals to know for sure. Some feedback on this approach would be appreciated.

The Lua config has an entry point when no plugins have been loaded and the NeoVim instance has a clean slate, right? At this point, the initialization routine could compare the NeoVim version with the LunarVim version. If there is a version mismatch between NeoVim and LunarVim (such as NeoVim 0.9 running LunarVim 1.2) the user could be warned about the incompatibility and the fact that they might be better off downgrading NeoVim until a new branch of LunarVim is available to avoid annoying deprecation warnings and unexpected problems. They should be able to snooze this warning until next major release of NeoVim instead of just acknowledging it so they don't get the same warning each time they run LunarVim.

When a new branch is available, the legacy branch repositories could be updated so the incompatibility warning offers to upgrade LunarVim and includes an upgrade-mode lua file. Of course, the user wouldn't see the revised warning until after they do a minor update, but it's better than nothing. 

There could also be a configuration option that enables automatic checks for minor updates. If that flag is set, that check could be performed at the end of startup, preferably in another thread. Then the availability of an update could be flagged in a local file and the user could receive a status bar message or icon (or both) indicating the presence of a minor update or major upgrade. 

On the next start after that, the initialization routine could let the user know it's safe to upgrade NeoVim to the latest version (if it's older), automatically start the LunarVim upgrade, or prompt the user for permission to upgrade (depending on configuration settings and the version of NeoVim).

_Here's the important part:_

If an upgrade is called for at this early point in the initialization process, the upgrade-mode lua file could be copied to a temporary location and any plugins it requires could also be installed to the same temporary location. Then control could be passed to that upgrade-mode lua file. This file would not rely on the standard installation location for anything, so it would be safe for it to switch branches and make whatever other changes need to be made to accommodate the new branch (like resetting plugin cache or whatever else). Then the upgrade-mode lua file could confirm the process completed successfully, remove any temporary plugins and reset any configuration settings that it made, then pass control to the new branch's initialization point. While all that work is taking place, the upgrade-mode lua file could display a full screen buffer with a progress bar and status messages and prompt the user for responses when necessary.

I hope I explained that well. The upgrade would still disrupt any other running instances of LunarVim, so the upgrade-mode lua file could have a step that checks for them and prompts with a warning that they will crash if they aren't closed. It might be able to attempt to close them as well, with permission from the user, but then you get into questions about what to do if files are not saved. It's probably better to warn and let the user force the upgrade if they must.

Does this sound like a possibility?

**Comment by FlippingBinary** [comment]
@kobzar as you know, LunarVim has a great community. If you're having trouble setting up DAP for Rust in LunarVim, you can open a new issue describing what you've done, what you expect, and what's actually happening. Someone will almost certainly chime in with a solution.

However, the process I described is one that I would be willing to refine and develop a proof of concept, if the LunarVim team is receptive, so I don't think it would have an impact on the development of DAP-related integrations. It's also an improvement that would be beneficial during every upgrade in the future, not just the most recent one that is the subject of this issue. That being said, they seem to be favoring an external package management approach. Hopefully that solves the difficulty of upgrading in the future.

**Comment by kobzar** [comment]
> @kobzar as you know, LunarVim has a great community. If you're having trouble setting up DAP for Rust in LunarVim, you can open a new issue describing what you've done, what you expect, and what's actually happening. Someone will almost certainly chime in with a solution.
> 
> However, the process I described is one that I would be willing to refine and develop a proof of concept, if the LunarVim team is receptive, so I don't think it would have an impact on the development of DAP-related integrations. It's also an improvement that would be beneficial during every upgrade in the future, not just the most recent one that is the subject of this issue. That being said, they seem to be favoring an external package management approach. Hopefully that solves the difficulty of upgrading in the future.

For what future you are see the 1.2 release lvim? Did you read what are iM say before?

**Comment by brneor** [comment]
> **You are ask the same as update ubuntu to arch linux.**

This is plain dishonesty and an awful analogy. No one is trying to update Ubuntu to Arch as no one is trying to update Lunarvim to Doom Emacs.

People are just expecting to update from a version of Lunarvim to another version of Lunarvim similar to a Ubuntu user updating from 22.10 to 23.04 which is fairly reasonable to ask.

**Comment by FlippingBinary** [comment]
> For what future you are see the 1.2 release lvim? Did you read what are iM say before?

LunarVim 1.2 is a legacy release. I don't imagine anyone will be spending much time making major improvements to it, but I didn't suggest anything that would be exclusive to LunarVim 1.2. The problem described by this issue is one that will repeat itself when the next major release of LunarVim comes out unless something is done to fix the upgrade process.

**Comment by LostNeophyte** [comment]
> I think an in-place upgrade process might be possible, but I'm not familiar enough with lua and NeoVim internals to know for sure. Some feedback on this approach would be appreciated.

It's probably possible, I'm just not sure if it's worth it. the installer, and initial bootstrapping is annoying to work on (not sure if others think the same, I can only speak for myself)

> The Lua config has an entry point when no plugins have been loaded and the NeoVim instance has a clean slate, right? At this point, the initialization routine could compare the NeoVim version with the LunarVim version. If there is a version mismatch between NeoVim and LunarVim (such as NeoVim 0.9 running LunarVim 1.2) the user could be warned about the incompatibility and the fact that they might be better off downgrading NeoVim until a new branch of LunarVim is available to avoid annoying deprecation warnings and unexpected problems. They should be able to snooze this warning until next major release of NeoVim instead of just acknowledging it so they don't get the same warning each time they run LunarVim.

we have something similar, it doesn't seem to work though https://github.com/LunarVim/LunarVim/blob/29f94e436120525be50b3676990dae7cbc351316/lua/lvim/utils/hooks.lua#L53

> When a new branch is available, the legacy branch repositories could be updated so the incompatibility warning offers to upgrade LunarVim and includes an upgrade-mode lua file. Of course, the user wouldn't see the revised warning until after they do a minor update, but it's better than nothing.

we can do that

> There could also be a configuration option that enables automatic checks for minor updates. If that flag is set, that check could be performed at the end of startup, preferably in another thread. Then the availability of an update could be flagged in a local file and the user could receive a status bar message or icon (or both) indicating the presence of a minor update or major upgrade.

That's too much imo

> On the next start after that, the initialization routine could let the user know it's safe to upgrade NeoVim to the latest version (if it's older), automatically start the LunarVim upgrade, or prompt the user for permission to upgrade (depending on configuration settings and the version of NeoVim).
> 
> _Here's the important part:_
> 
> If an upgrade is called for at this early point in the initialization process, the upgrade-mode lua file could be copied to a temporary location and any plugins it requires could also be installed to the same temporary location. Then control could be passed to that upgrade-mode lua file. This file would not rely on the standard installation location for anything, so it would be safe for it to switch branches and make whatever other changes need to be made to accommodate the new branch (like resetting plugin cache or whatever else). Then the upgrade-mode lua file could confirm the process completed successfully, remove any temporary plugins and reset any configuration settings that it made, then pass control to the new branch's initialization point. While all that work is taking place, the upgrade-mode lua file could display a full screen buffer with a progress bar and status messages and prompt the user for responses when necessary.

that's too complicated, it will be a pain to debug

> I hope I explained that well. The upgrade would still disrupt any other running instances of LunarVim, so the upgrade-mode lua file could have a step that checks for them and prompts with a warning that they will crash if they aren't closed. It might be able to attempt to close them as well, with permission from the user, but then you get into questions about what to do if files are not saved. It's probably better to warn and let the user force the upgrade if they must.
> 
> Does this sound like a possibility?

I would be in favor of such system but without update-mode

**Comment by LostNeophyte** [comment]
(response to kobzar)
---
> My opinion is make dot in this discussion. As we known neovim is fork of vim. Vim is absolute, but neovim give us the new fiches and make vim better. So, in my situation, i am migrate from vim to neovim everywhere and use vim only in old and specyfical systems. Sometime ago, we were from Packer to Mason/Lazy and develop the new release of lvim. This is it. We are dont need to spentour time to develop migration script from 1.2 to 1.3 release. My opinion we must spent time to make new 1.3 release more stable and productive. No one need 1.2 release now and wont need it in future.

the update functionality if we want to add it would work for all new versions, not just 1.2->1.3, the current process is unusual and confusing

> So, my proposition is next: 1.Leave 1.2 release as old and hide it on site and github - just for history. 2. On the install/update instruction on offcite and github add just one string: "For old users: To update from 1.2 to 1.3 uninstall/install lvim from actual link" Thats all.

1.2 reached EOL when 1.3 was released, we will only maintain master and latest stable version i agree here, but it should still be available on github

**Comment by LostNeophyte** [comment]
> That being said, they seem to be favoring an external package management approach. Hopefully that solves the difficulty of upgrading in the future

maintaining our own installer, uninstaller and updater takes a lot of time and package managers already exist, it would be way better if we used them instead imo

**Comment by kobzar** [comment]
> > For what future you are see the 1.2 release lvim? Did you read what are iM say before?
> 
> LunarVim 1.2 is a legacy release. I don't imagine anyone will be spending much time making major improvements to it, but I didn't suggest anything that would be exclusive to LunarVim 1.2. The problem described by this issue is one that will repeat itself when the next major release of LunarVim comes out unless something is done to fix the upgrade process.

Install ubuntu and wait when it update to arch. 

Neovim its like kernel in linux. Next is the package managers (the same as linux apt, pacman, yum) Package, Lazy,Mason, e.t.c
Lvim 1.2 and 1.3 use different package managers. Both of them has specifically moments. To upgrade lvim from 1.2 to 1.3 we must delete all install new branch with saved config.  
yes. We can spent a lot of time and make it in update script by lua code. But why?
Believe me, one year ago no one will know that lunarvim was 1.2 release. The same as now only 5 peoples know what was before 1.2 release
