### ISSUE TITLE
Should we remove nlsp settings?

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#4132]
I forget if I've asked this before

**Comment by quantumfate** [comment]
yes it barely supports anything useful

**Comment by meijieru** [comment]
It enables an easy way to customize the lsp per project.

**Comment by chaozwn** [comment]
> It enables an easy way to customize the lsp per project.

hi, guy. can you tell the way  how to customize the lsp.

**Comment by nieomylnieja** [comment]
> yes it barely supports anything useful

that's a very shallow statement, bear in mind it's used to configure LSP servers themselves, not the nvim wrapper for them (like filetype options). It supports all the major LSPs out there, so again, not really sure what are you basing your opinion on. As @meijieru mentioned, it also allows an easy way to manage per project config.
It is definitely not sth and average user would ever use though, maybe it's a bit of an overkill to have it maintained within LunarVim. On the other hand I'm not sure how much of a pain would it be to add it outside of the lsp setup within lvim core, If it's to be removed, I'd definitely explain in the example plugin configurations on how to configure it.

**Comment by LostNeophyte** [comment]
pros and cons of removing it that I can think of at the moment:
+ it's barely maintained, the readme still uses lsp-installer in the examples instead of mason, there's a two month old pr to fix that with no comments from the maintainer
+ most users probably don't know how and don't use it
- breaking change
- I prefer nlsp-settings over our way of configuring lsp servers, it requires way less effort and there's completion

we could switch to  [folke/neoconf](https://github.com/folke/neoconf.nvim) instead
