### ISSUE TITLE
lvim.transparent_window makes background black (replaces theme bg to black)

### ISSUE THREAD

**Issue by 1-800-jono** [LunarVim/LunarVim#4254]
Not sure this is a bug or if it's actually expected but I noticed that when setting `lvim.transparent_window` to `true` it makes the current theme's background completely black (#000000). 

I would expect that the theme's background would stay the same color and be able to add transparency. So if, for example, the theme's background is red then adding transparency would just leave it red then be able to adjust transparency with terminal options.

**Comment by LostNeophyte** [comment]
that option sets the background to none, so that would be your terminals background. I believe terminals don't support setting transparent colors in cells, if neovim set the background color it then couldn't be transparent.

in some teminals if you set the background color of your terminal to the same one as the one in neovim you'll get what you want, you can do that automatically with typicode/bg.nvim

example: alacritty on the left, kitty on the right
I have lvim.transparent_window set to false
on the left you can see that the padding of the terminal is transparent(look at thebottom right of the window), but the nvim background isn't
on the right the terminal padding and nvim background are transparent but the current line isn't
![image](https://github.com/LunarVim/LunarVim/assets/110467150/3138d757-4763-43cb-b109-2e8fdc8c4f27)

if i set lvim.transparent_window to true this happens, kitty hasn't changed, but alacritty now looks the same as kitty
![image](https://github.com/LunarVim/LunarVim/assets/110467150/0dfd1cf4-3e28-455a-93c8-db402af88192)

I suggest using typicode/bg.nvim or setting your terminal bg to the neovim one, make sure your terminal is transparent even before running nvim
