### ISSUE TITLE
Development server with multiple developers

### ISSUE THREAD

**Issue by ecerichter** [LunarVim/LunarVim#4286]
We have a development server dedicated to developers (which they access with ssh).
How to share lunarvim install, letting each developer to customize theme, shortcuts, etc. from a default base configuration.
I mean, a place like bash (/etc/bashrc is a global config, and each user can have customizations at ~/.bashrc).
Is that possible? May be this is more a "neovim" question than a "lunarvim"...

**Comment by kobzar** [comment]
You cand do this. 
User config is consist not only key bindings. The plugins, lsp, linter and formating tools to. 
So, each user has personal dirs like .local/share/lvim .config/lvim with their data. 
What the problem to install lvim for each user directly?
(you can clone the git and run install local like bash install.sh)

**Comment by ecerichter** [comment]
Well, point is, we have developers who are not used to the Linux installation process, and I would like to reduce friction in adopting lvim - so sharing the base config would easy my task as sys admin - and also make easier when need to update tooling.
But it's ok - was just checking if possible.
Thanks!

**Comment by LostNeophyte** [comment]
It could be possible, but the users would need to set some settings differently e.g. if you add plugins in the global config the users would need to insert their plugins to the table instead of setting the table. Unless the global config would be loaded after the local one but then it would take priority over the local one. Would one of these options satisfy your needs?
