### ISSUE TITLE
empty config file on linux mint 21.2

### ISSUE THREAD

**Issue by aum7** [LunarVim/LunarVim#4314]
### Problem description

from official page :
https://www.lunarvim.org/docs/configuration
i did
$ cp ~/.local/share/lunarvim/lvim/utils/installer/config.example.lua ~/.config/lvim/config.lua
but the resulting file is empty, as is source file :
-- Read the docs: https://www.lunarvim.org/docs/configuration
-- Video Tutorials: https://www.youtube.com/watch?v=sFA9kX-Ud_c&list=PLhoH5vyxr6QqGu0i7tt_XoVK9v-KvZ3m6
-- Forum: https://www.reddit.com/r/lunarvim/
-- Discord: https://discord.com/invite/Xb9B4Ny

where can i get sample config file ?

thx for sharing, love the lunar vim, it rocks !

aum
s love nia

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.0)

NVIM v0.9.1 release

### Terminal name

linux mint default terminal

### Operating system/version

linux mint 21.2

**Comment by LostNeophyte** [comment]
that is the current default config file since https://github.com/LunarVim/LunarVim/commit/72e55a729015130b68afdbf433ed349ece491909, I'll probably end up adding some examples to it, but not as many as before, here's the old version https://github.com/LunarVim/LunarVim/blob/75ba51cb0feabdd3590979e60e088e977cf2713c/utils/installer/config.example.lua
don't close the issue, i'll use it as a reminder to add the examples

**Comment by aum7** [comment]
thx for reply
will not close the issue
either notify me when issue is to be closed, or, if at all an option, close it yourself, i trust ?

godspeed

have fun

aum

**Comment by LostNeophyte** [comment]
I'll close it
