### ISSUE TITLE
Randomized Color Scheme "Lunar"

### ISSUE THREAD

**Issue by rahul-goel** [LunarVim/LunarVim#4339]
### Problem description

LunarVim uses the default colorscheme called "lunar" which looks like the first image attached. And most of the times when I launch lunarvim, it is the default colorscheme. But sometimes, just sometimes it launches with a different colorscheme under the same name "lunar". And this one looks and feels a 100x better to me and I want to use this forever (second image attached).

I have also attached a video indicating the issue. Note that in the video, I get the colorscheme of my liking first.

I've tried resetting the colorscheme from the vim commandine as well as the telescope interface. In both cases, it remains the same as the one it launched with.

I've tried using two different terminals: my default st terminal, and a freshly installed wezterm terminal as well. The issue persists.

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.0)

NVIM v0.9.1

### Terminal name

st,wezterm

### Operating system/version

Arch Linux (6.4.11-arch2-1)

### Steps to reproduce

Try launching LunarVim multiple times. Randomly in one instance, it will pop up with a different colorscheme.

### Screenshots

![pic-window-230825-1523-58](https://github.com/LunarVim/LunarVim/assets/54021162/0fc46896-38e6-474d-b0af-8410516a23e5)
![pic-window-230825-1523-50](https://github.com/LunarVim/LunarVim/assets/54021162/a585d0ff-e31e-408f-a9ee-dc3f0117d41a)

https://github.com/LunarVim/LunarVim/assets/54021162/bd6694bf-7479-433f-83c5-05284a556631

**Comment by rahul-goel** [comment]
If anyone could point me to the colorscheme in the second image, that would be great as well. I love it.

**Comment by rahul-goel** [comment]
Any update?

**Comment by gchamon** [comment]
hey @rahul-goel, I know this is a stale issue and you probably have already moved on, but for future reference the difference you are seeing is because of lazy load of colorscheme packages.

The first one is the "lunar" colorscheme from https://github.com/LunarVim/lunar.nvim

![Image](https://github.com/user-attachments/assets/0509f33a-5fdc-41f9-aa1f-14f4372b9ca0)

The second one is also "lunar" but this time from https://github.com/LunarVim/Colorschemes

![Image](https://github.com/user-attachments/assets/405f88a4-1a3f-4d1b-a815-63d537b613ef)

**Comment by rahul-goel** [comment]
Thank you! @gchamon 🙌
