### ISSUE TITLE
LunarVim Python Dependency Installation Error: externally-managed-environment

### ISSUE THREAD

**Issue by dvsociety** [LunarVim/LunarVim#4403]
### Problem description

I was trying to install LunarVim's Python dependencies on my Arch Linux system. Specifically, when prompted with the question: "Would you like to install LunarVim's Python dependencies: pynvim?", I opted for "yes". However, I encountered the following error:

```
Verifying that pip is available..
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

subprocess.CalledProcessError: Command '['/usr/bin/python3', '-W', 'ignore::DeprecationWarning', '-c', ...
']' returned non-zero exit status 1.
[WARN]: skipping installing optional python dependencies

```

I am seeking guidance on how to correctly handle and resolve this error. Is this something related to LunarVim, or is it more specific to the Python environment management on Arch Linux? Any help or direction would be greatly appreciated.

### LunarVim version

last

### Neovim version (>= 0.9.1)

0.9.4

### Terminal name

kitty

### Operating system/version

Arch Linux

**Comment by PuppyGirlBelly** [comment]
A workaround for this is to manually install the (so far only) python dependency, 'pynvim'. You can do so on Arch with the following command;
`sudo pacman -S python-pynvim`

Then install LunarVim again, selecting "no" for installing python dependencies.

**Comment by Curricane** [comment]
This is a limitation of archlinux package management, using pip to install python packages to break pacman downloaded python packages. You need to create a python environment and install it. I installed anaconda via yay and installed lvim in the conda python3 environment and it was a direct success

**Comment by mfouesneau** [comment]
The docker example on the website throws the same error.

**Comment by SaadAhmedGit** [comment]
> A workaround for this is to manually install the (so far only) python dependency, 'pynvim'. You can do so on Arch with the following command; `sudo pacman -S python-pynvim`
> 
> Then install LunarVim again, selecting "no" for installing python dependencies.

Still didn't work

**Comment by hirmanmaksim** [comment]
Current confirmation on macOS (Apple Silicon): Homebrew Python 3.14.7 with pip 26.2.1 still fails when installing `release-1.4/neovim-0.9` (the installer prompts for `pynvim`).

The branch installer calls `python3 -m ensurepip`, then `python3 -m pip install --user pynvim`; Homebrew marks this interpreter externally managed, so `ensurepip` and the subsequent pip install fail with PEP 668’s `externally-managed-environment` error. The installer exits rather than treating this optional dependency as skipped.

`pynvim` installs successfully in an ordinary venv with this Python version, so this is not a package compatibility issue. The current `master` installer has removed the Python dependency step entirely. Could that removal, or at least a non-fatal skip with an explanation that `pynvim` is optional, be backported to the 1.4 installer branch?

Workaround: rerun the installer and answer `n` to the Python dependency prompt. Do not use `--break-system-packages` or remove Homebrew’s `EXTERNALLY-MANAGED` marker.
