### ISSUE TITLE
Icons are not visible properly

### ISSUE THREAD

**Issue by BtAbdul** [LunarVim/LunarVim#4407]
### Problem description

Icons are not visible proper as expected, 20% of icon is faded and overlap with respective content
For example of NTree
![IMG_20231106_090155](https://github.com/LunarVim/LunarVim/assets/46757797/b6ab1c8d-794f-498b-9ee2-2b16dcd3891e)

Telescope 🔭
![IMG_20231106_090235](https://github.com/LunarVim/LunarVim/assets/46757797/eb79eb01-0781-4196-91e7-14b2e76671e3)

statusbar
![IMG_20231106_090349](https://github.com/LunarVim/LunarVim/assets/46757797/464ee2a9-509e-4c2e-9dc1-41d30838de33)

I tried different Nord font bust its some issues. It seems not related with Nord fonts,  Nord font suppose to display icons which fine. 

### LunarVim version

master-15dc5292-dirty

### Neovim version (>= 0.9.1)

NVIM v0.9.4 Build type: Release

### Terminal name

termux (android)

### Operating system/version

android

**Comment by BtAbdul** [comment]
Little arrow ↗️ icon in telescope is not visible

**Comment by chase** [comment]
@BtAbdul This isn't a bug with LunarVim.

This is a problem with either your terminal emulator and/or your font. The glyphs are double-width characters and it seems they are getting clipped.

You can patch your font to use single width characters: https://hub.docker.com/r/nerdfonts/patcher

Obviously if you're on Android you don't have many choices for terminal emulators, so that's probably your best bet.
