### ISSUE TITLE
GUI(Neovide) crashes due to invalid 'guifont' option

### ISSUE THREAD

**Issue by wy-z** [LunarVim/LunarVim#4446]
### Problem description

- The value of 'guifont' is unreasonable; 'monospace:h17' is not a universally pre-installed font on most devices.
- Neovide will cache the font when there is a change in 'guifont' to improve rendering performance, and an incorrect value can cause it to malfunction.

An erroneous 'guifont' configuration may lead to GUI operational errors;
I have also reconfigured 'guifont' in my personal settings, but the default configuration in 'lvim' still triggers a 'guifont' change once, see https://github.com/LunarVim/LunarVim/blob/master/lua/lvim/config/settings.lua#L22 .

Neovide: https://github.com/neovide/neovide
Neovide font caching: https://github.com/neovide/neovide/blob/af9869bd6d8d3434b187e29f85032ee74e40b536/src/renderer/fonts/caching_shaper.rs#L44C6-L44C19

### LunarVim version

master-b124e8c3

### Neovim version (>= 0.9.1)

v0.9.4

### Terminal name

iTerm2

### Operating system/version

14.2.1 (23C71)

### Screenshots

<img width="408" alt="image" src="https://github.com/LunarVim/LunarVim/assets/4213483/62283f9e-c007-48cd-a0ac-487dd1f24562">

**Comment by xinleibird** [comment]
Same issue, the reason for this is a feature that was added in Neovide v0.12.0: "Report error when setting a wrong guifont value" (https://github.com/neovide/neovide/pull/2089), in macOS Sonoma "monospace" is not considered a legal font in Neovide v0.12.0.

Probably shouldn't set guifont in LunarVim? because LunarVim is indeed not related to the GUI?

**Comment by wy-z** [comment]
https://github.com/LunarVim/LunarVim/pull/4447
