### ISSUE TITLE
Telescope dependencies are missing from windows installations 

### ISSUE THREAD

**Issue by The-Noumeno** [LunarVim/LunarVim#4450]
### Problem description

I recently installed lunar vim under Windows, and I immediately noticed that telescope was not installing correctly, turns out you need to install ripgrep (and also sharkdp/fd), otherwise telescope won't work properly. I think this should be included into the installation instructions for Windows explicitely (in the download page on the main site at least), because it is not at all obvious at a first glance! 

### LunarVim version

-

### Neovim version (>= 0.9.1)

0.9

### Terminal name

Powershell 7+

### Operating system/version

Windows

### Steps to reproduce

Simply install with the script provided on the main page on a fresh install Windows machine

**Comment by AndrewJRichardson** [comment]
Much of the windows guide needs revisiting here are the issues I encountered on top of the ones you have mentioned:

If you use make like the prerequisites suggest then there is also an unmentioned requirement to have gcc or clang installed to compile telescope-fzf-native.nvim.

The config file for the current stable version (1.3) is broken by default in Windows. This was seemingly fixed in June but there hasn't been a release since.  `-NoLogo` needs removing from the line `vim.opt.shell = "pwsh.exe -NoLogo"`

I've also found that Lazy wont pickup new plugins until I restart lvim but that is possibly an issue I have caused.

**Comment by foolofdestiny** [comment]
when u installed lunarvim did you use self installer and have it  run through its check dependancies?
my understand is ripgrep is a/the reason cargo is listed on the main install page

Prerequisites
Make sure you have installed the latest version of Neovim v0.9.0+.
Have git, make, pip, python, npm, node and *_cargo_ * installed on your system.

through the lunarvim install script cargo _should_ self install ripgrep 

are you saying that didnt happen?

**Comment by kylo252** [comment]
These were not hard-dependencies back when we wrote the installer script.

Please create a PR to add them to this list here: https://github.com/LunarVim/LunarVim/blob/e85637c2408264f2591b9c9bca073cd58d314a97/utils/installer/install.ps1#L88-L89

**Comment by honeway** [comment]
I didn't install make and gcc. Use VS Build Tools and cmake instead.

```lua
{ 'nvim-telescope/telescope-fzf-native.nvim', build = 'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build' }
```
