### ISSUE TITLE
How can i disable auto-expanding of a funciton's signature in completion?

### ISSUE THREAD

**Issue by zsmatrix62** [LunarVim/LunarVim#4565]
### Problem description

In code completion, how can i disable the sinppets of auto expanding fo a funciton's signature? This did not happen in my pre self-configured nvim, but always in Lunarvim .. 

As you can tell from below, when i complete the compeltion, the function's signature expands automatically as placehoders ... I have to remove them manually each time when i call any methods or function ...

<img width="582" alt="图片" src="https://github.com/LunarVim/LunarVim/assets/2951879/ee5909f0-5330-4c56-ba0f-eb3f55e8e23d">

<img width="484" alt="图片" src="https://github.com/LunarVim/LunarVim/assets/2951879/ed1ff0dd-4731-44fb-a595-79fc21696fe1">

### LunarVim version

latest

### Neovim version (>= 0.9.1)

0.10.0

### Terminal name

Alacritty

### Operating system/version

macOS

**Comment by kylo252** [comment]
I think you might be confusing how the feature works, neovim is already in "replace" mode when you trigger the autocomplete so you can start writing directly and it would replace the text. From there, you can press <tab> to jump to the next place holder.

Otherwise, take a look at `nvim-cmp`'s configuration and set it how you'd like in `lvim.builtin.cmp` or consider checking what options are available through the language server, see: https://github.com/hrsh7th/nvim-cmp/issues/645.
